import { StrictMode, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import catalogData from "../../packages/catalog.json";
import tmuxConfigRaw from "../../common/.tmux.conf?raw";
import vimConfigRaw from "../../common/.vimrc?raw";
import zshConfigRaw from "../../common/.zshrc?raw";
import "./styles.css";

const REPO_OWNER = "goznauk";
const REPO_NAME = "dotfiles";
const DEFAULT_REF = "main";

type OsId = "ubuntu" | "macos" | "amazon" | "rhel";
type ViewId = "install" | "configs" | "summary";
type InstallStepKey = "packages" | "shell" | "dotfiles" | "tools";
type DockerStrategyId = "official" | "distro" | "podman" | "none";
type NodeStrategyId = "mise" | "nvm" | "none";
type PythonStrategyId = "system-uv" | "mise" | "none";
type JavaStrategyId = "mise-temurin-21" | "distro-openjdk-21" | "none";
type ConfigKey = "zshrc" | "vimrc" | "tmux" | "htop";
type DraggedBlock = { configKey: ConfigKey; blockId: string } | null;

type OsTarget = {
  id: OsId;
  label: string;
  packageManager: string;
  commandTarget: string;
  implemented: boolean;
  note: string;
};

type PackageGroup = {
  id: string;
  title: string;
  description: string;
  defaultEnabled: boolean;
};

type CatalogPackage = {
  id: string;
  group: string;
  label: string;
  defaultSelected: boolean;
  packages: Record<OsId, string[]>;
  note?: string;
};

type Strategy = {
  id: string;
  label: string;
  description: string;
  defaults?: OsId[];
};

type ConfigBlock = {
  id: string;
  title: string;
  description: string;
  shortcuts: string[];
  enabled: boolean;
  content: string;
};

type ConfigBlockTemplate = Omit<ConfigBlock, "enabled" | "content"> & {
  start: number;
  end: number;
  enabled?: boolean;
};

type Catalog = {
  osTargets: OsTarget[];
  groups: PackageGroup[];
  packages: CatalogPackage[];
  strategies: {
    docker: Strategy[];
    node: Strategy[];
    python: Strategy[];
    java: Strategy[];
  };
};

const catalog = catalogData as Catalog;

const installSteps: Array<{
  key: InstallStepKey;
  title: string;
  description: string;
  skipFlag: string;
}> = [
  {
    key: "packages",
    title: "OS packages",
    description: "Install package-manager packages selected from the catalog.",
    skipFlag: "--skip-apt"
  },
  {
    key: "shell",
    title: "Shell setup",
    description: "oh-my-zsh, Powerlevel10k, syntax highlighting, autosuggestions.",
    skipFlag: "--skip-shell"
  },
  {
    key: "dotfiles",
    title: "Dotfile links",
    description: "Link zsh, Vim, tmux, Git config, and Git exclude files.",
    skipFlag: "--skip-dotfiles"
  },
  {
    key: "tools",
    title: "Runtime tools",
    description: "uv, Rust stable, rustfmt, clippy, and selected language runtimes.",
    skipFlag: "--skip-tools"
  }
];

const htopConfigDefault = `# htop config generated by dotfiles chooser
fields=0 48 17 18 38 39 2 46 47 49 1
sort_key=46
sort_direction=1
tree_sort_key=0
tree_sort_direction=1
hide_kernel_threads=1
hide_userland_threads=0
shadow_other_users=0
show_thread_names=0
show_program_path=1
highlight_base_name=1
highlight_megabytes=1
highlight_threads=1
highlight_changes=0
highlight_changes_delay_secs=5
find_comm_in_cmdline=1
strip_exe_from_cmdline=1
show_merged_command=0
header_margin=1
detailed_cpu_time=0
cpu_count_from_one=0
show_cpu_usage=1
show_cpu_frequency=1
show_cpu_temperature=0
degree_fahrenheit=0
update_process_names=0
account_guest_in_cpu_meter=0
color_scheme=0
enable_mouse=1
delay=15
left_meters=LeftCPUs2 Memory Swap
left_meter_modes=1 1 1
right_meters=RightCPUs2 Tasks LoadAverage Uptime
right_meter_modes=1 2 2 2
`;

const createConfigBlocks = (raw: string, templates: ConfigBlockTemplate[]): ConfigBlock[] => {
  const lines = raw.trimEnd().split(/\r?\n/);
  return templates.map((template) => ({
    id: template.id,
    title: template.title,
    description: template.description,
    shortcuts: template.shortcuts,
    enabled: template.enabled ?? true,
    content: `${lines.slice(template.start - 1, template.end).join("\n")}\n`
  }));
};

const configDefinitions: Record<
  ConfigKey,
  { title: string; path: string; mkdir?: string; blocks: ConfigBlock[] }
> = {
  zshrc: {
    title: ".zshrc",
    path: "$HOME/.zshrc",
    blocks: createConfigBlocks(zshConfigRaw, [
      {
        id: "prompt",
        title: "Prompt bootstrap",
        description: "Loads the Powerlevel10k instant prompt before the rest of the shell starts.",
        shortcuts: [],
        start: 1,
        end: 7
      },
      {
        id: "history",
        title: "History settings",
        description: "Keeps a large shared history and avoids repeated duplicate commands.",
        shortcuts: [],
        start: 9,
        end: 13
      },
      {
        id: "plugins",
        title: "oh-my-zsh plugins",
        description: "Enables Git helpers, Docker helpers, dotenv loading, completions, and suggestions.",
        shortcuts: [],
        start: 15,
        end: 18
      },
      {
        id: "path",
        title: "PATH order",
        description: "Puts local user tools, Cargo tools, and home bin ahead of system paths.",
        shortcuts: [],
        start: 20,
        end: 31
      },
      {
        id: "framework",
        title: "Shell framework",
        description: "Loads oh-my-zsh when available and falls back to plain completion setup.",
        shortcuts: [],
        start: 33,
        end: 38
      },
      {
        id: "runtime-hooks",
        title: "Runtime hooks",
        description: "Activates mise and direnv in interactive shells when those tools exist.",
        shortcuts: [],
        start: 40,
        end: 46
      },
      {
        id: "environment",
        title: "Environment",
        description: "Sets locale, editor, visual editor, and GPG tty defaults.",
        shortcuts: [],
        start: 48,
        end: 52
      },
      {
        id: "history-search",
        title: "History search keys",
        description: "Makes Up and Down search matching command history from the current prefix.",
        shortcuts: ["Up", "Down"],
        start: 54,
        end: 58
      },
      {
        id: "safe-aliases",
        title: "Prompted aliases",
        description: "Keeps raw rm, cp, and mv untouched, and adds explicit prompted variants.",
        shortcuts: ["rmi", "rmri", "cpi", "mvi"],
        start: 60,
        end: 65
      },
      {
        id: "navigation",
        title: "Navigation and listings",
        description: "Adds short directory and listing aliases used during terminal work.",
        shortcuts: ["cd..", "l", "ll", "la"],
        start: 67,
        end: 72
      },
      {
        id: "tmux-docker",
        title: "tmux and Docker aliases",
        description: "Adds the session attach flow and common Docker Compose shortcuts.",
        shortcuts: ["ta 0", "ta0", "tls", "tn"],
        start: 74,
        end: 80
      },
      {
        id: "editors",
        title: "Edit helpers",
        description: "Adds quick commands for editing and applying the shell configuration.",
        shortcuts: ["zshrc", "zshrc_apply"],
        start: 82,
        end: 83
      },
      {
        id: "inspection",
        title: "Inspection helpers",
        description: "Adds compact helpers for listening ports, IP addresses, and PATH entries.",
        shortcuts: ["ports", "ipb", "pathls"],
        start: 85,
        end: 95
      },
      {
        id: "local-prompt",
        title: "Local prompt file",
        description: "Loads the generated Powerlevel10k local prompt file when it exists.",
        shortcuts: [],
        start: 97,
        end: 97
      }
    ])
  },
  vimrc: {
    title: ".vimrc",
    path: "$HOME/.vimrc",
    blocks: createConfigBlocks(vimConfigRaw, [
      {
        id: "core",
        title: "Core mode",
        description: "Starts Vim in modern mode with filetype plugins, indentation, and syntax.",
        shortcuts: [],
        start: 1,
        end: 3
      },
      {
        id: "encoding",
        title: "Encoding and files",
        description: "Sets UTF-8 defaults, safer bells, autoread, hidden buffers, swap, and undo files.",
        shortcuts: [],
        start: 5,
        end: 16
      },
      {
        id: "indent",
        title: "Indentation",
        description: "Uses two-space indentation by default with expanded tabs.",
        shortcuts: [],
        start: 18,
        end: 24
      },
      {
        id: "search",
        title: "Search behavior",
        description: "Enables incremental smart-case search and a quick mapping to clear highlights.",
        shortcuts: ["leader", "Space"],
        start: 26,
        end: 30
      },
      {
        id: "performance",
        title: "Completion and redraw",
        description: "Keeps completion local and avoids unnecessary redraw work.",
        shortcuts: [],
        start: 32,
        end: 34
      },
      {
        id: "interface",
        title: "Interface",
        description: "Shows status, ruler, line numbers, command feedback, title, mouse, and colors.",
        shortcuts: [],
        start: 36,
        end: 46
      },
      {
        id: "plugins",
        title: "vim-plug setup",
        description: "Bootstraps vim-plug and installs only vim-sensible plus EditorConfig support.",
        shortcuts: [":PlugInstall"],
        start: 48,
        end: 59
      },
      {
        id: "filetypes",
        title: "Filetype indentation",
        description: "Overrides indentation for common web, Ruby, and Python files.",
        shortcuts: [],
        start: 61,
        end: 64
      }
    ])
  },
  tmux: {
    title: ".tmux.conf",
    path: "$HOME/.tmux.conf",
    blocks: createConfigBlocks(tmuxConfigRaw, [
      {
        id: "prefix",
        title: "Prefix and reload",
        description: "Uses Ctrl-A as the prefix and binds reload to prefix plus r.",
        shortcuts: ["C-a", "C-a r"],
        start: 1,
        end: 6
      },
      {
        id: "session",
        title: "Session behavior",
        description: "Enables mouse support, focus events, clipboard, renumbering, and deep history.",
        shortcuts: [],
        start: 8,
        end: 15
      },
      {
        id: "indexes",
        title: "Indexes",
        description: "Starts windows and panes at 1 for easier keyboard targeting.",
        shortcuts: ["1"],
        start: 17,
        end: 19
      },
      {
        id: "windows",
        title: "Windows and panes",
        description: "Adds pane splits, vim-style pane movement, window navigation, and resize keys.",
        shortcuts: ["c", "|", "-", "h", "j", "k", "l", "Tab"],
        start: 21,
        end: 38
      },
      {
        id: "copy",
        title: "Copy mode",
        description: "Uses vi copy mode and tries common Linux clipboard tools before falling back.",
        shortcuts: ["v", "y", "Enter"],
        start: 40,
        end: 45
      },
      {
        id: "status",
        title: "Status line",
        description: "Sets a compact status line with host, session, date, time, window, and pane.",
        shortcuts: [],
        start: 47,
        end: 59
      },
      {
        id: "tpm",
        title: "TPM block",
        description: "Keeps the tmux plugin manager block available but commented by default.",
        shortcuts: ["prefix", "I"],
        start: 61,
        end: 65
      }
    ])
  },
  htop: {
    title: "htoprc",
    path: "$HOME/.config/htop/htoprc",
    mkdir: "$HOME/.config/htop",
    blocks: createConfigBlocks(htopConfigDefault, [
      {
        id: "columns",
        title: "Columns and sorting",
        description: "Chooses the visible process columns and sorts by memory usage.",
        shortcuts: ["F6"],
        start: 1,
        end: 5
      },
      {
        id: "visibility",
        title: "Visibility",
        description: "Controls thread display, merged commands, highlighting, and path behavior.",
        shortcuts: ["H", "K"],
        start: 6,
        end: 24
      },
      {
        id: "runtime",
        title: "Runtime display",
        description: "Sets color scheme, mouse support, refresh delay, and CPU display behavior.",
        shortcuts: ["F2", "F9"],
        start: 25,
        end: 31
      },
      {
        id: "meters",
        title: "Header meters",
        description: "Shows CPU, memory, swap, task, load, and uptime meters.",
        shortcuts: [],
        start: 32,
        end: 35
      }
    ])
  }
};

const createInitialConfigBlocks = () =>
  Object.fromEntries(
    (Object.keys(configDefinitions) as ConfigKey[]).map((key) => [
      key,
      configDefinitions[key].blocks.map((block) => ({ ...block }))
    ])
  ) as Record<ConfigKey, ConfigBlock[]>;

const createInitialActiveBlocks = () =>
  Object.fromEntries(
    (Object.keys(configDefinitions) as ConfigKey[]).map((key) => [key, configDefinitions[key].blocks[0].id])
  ) as Record<ConfigKey, string>;

const buildConfigContent = (blocks: ConfigBlock[]) =>
  blocks
    .filter((block) => block.enabled)
    .map((block) => block.content.trimEnd())
    .filter(Boolean)
    .join("\n\n")
    .concat("\n");

const shellQuote = (value: string) => `'${value.replaceAll("'", "'\\''")}'`;

const splitCustomPackages = (value: string) =>
  value
    .split(/[,\s]+/)
    .map((item) => item.trim())
    .filter(Boolean);

const unique = (items: string[]) => Array.from(new Set(items.filter(Boolean)));

const defaultDockerStrategy = (osId: OsId): DockerStrategyId => {
  const strategy = catalog.strategies.docker.find((item) => item.defaults?.includes(osId));
  return (strategy?.id as DockerStrategyId | undefined) ?? "none";
};

const packageNamesForOs = (item: CatalogPackage, osId: OsId) => item.packages[osId] ?? [];

const initialParams =
  typeof window === "undefined" ? new URLSearchParams() : new URLSearchParams(window.location.search);

const readInitialView = (): ViewId => {
  const view = initialParams.get("view");
  return view === "configs" || view === "summary" || view === "install" ? view : "install";
};

const readInitialOs = (): OsId => {
  const os = initialParams.get("os");
  return catalog.osTargets.some((target) => target.id === os) ? (os as OsId) : "ubuntu";
};

const readInitialConfig = (): ConfigKey => {
  const config = initialParams.get("config");
  return config === "vimrc" || config === "tmux" || config === "htop" || config === "zshrc"
    ? config
    : "zshrc";
};

function App() {
  const initialOs = readInitialOs();
  const [activeView, setActiveView] = useState<ViewId>(readInitialView);
  const [activeOs, setActiveOs] = useState<OsId>(initialOs);
  const [selectedPackageIds, setSelectedPackageIds] = useState<string[]>(
    catalog.packages.filter((item) => item.defaultSelected).map((item) => item.id)
  );
  const [expandedGroups, setExpandedGroups] = useState<Record<string, boolean>>(
    Object.fromEntries(catalog.groups.map((group, index) => [group.id, index < 3]))
  );
  const [stepSelection, setStepSelection] = useState<Record<InstallStepKey, boolean>>({
    packages: true,
    shell: true,
    dotfiles: true,
    tools: true
  });
  const [query, setQuery] = useState("");
  const [customPackages, setCustomPackages] = useState("");
  const [dockerStrategy, setDockerStrategy] = useState<DockerStrategyId>(() => {
    const strategy = defaultDockerStrategy(initialOs);
    return strategy === "none" ? "official" : strategy;
  });
  const [dockerEnabled, setDockerEnabled] = useState(
    initialParams.get("docker") === "off" ? false : defaultDockerStrategy(initialOs) !== "none"
  );
  const [nodeStrategy, setNodeStrategy] = useState<NodeStrategyId>("mise");
  const [pythonStrategy, setPythonStrategy] = useState<PythonStrategyId>("system-uv");
  const [javaStrategy, setJavaStrategy] = useState<JavaStrategyId>("mise-temurin-21");
  const [javaEnabled, setJavaEnabled] = useState(false);
  const [installTpm, setInstallTpm] = useState(false);
  const [assumeYes, setAssumeYes] = useState(true);
  const [repoRef, setRepoRef] = useState(DEFAULT_REF);
  const [copied, setCopied] = useState<string | null>(null);
  const [activeConfig, setActiveConfig] = useState<ConfigKey>(readInitialConfig);
  const [configBlocks, setConfigBlocks] = useState<Record<ConfigKey, ConfigBlock[]>>(createInitialConfigBlocks);
  const [activeConfigBlockIds, setActiveConfigBlockIds] =
    useState<Record<ConfigKey, string>>(createInitialActiveBlocks);
  const [draggedBlock, setDraggedBlock] = useState<DraggedBlock>(null);

  const activeTarget = catalog.osTargets.find((target) => target.id === activeOs) ?? catalog.osTargets[0];
  const selectedPackageItems = useMemo(
    () => catalog.packages.filter((item) => selectedPackageIds.includes(item.id)),
    [selectedPackageIds]
  );
  const customPackageList = useMemo(() => splitCustomPackages(customPackages), [customPackages]);
  const selectedPackageNames = useMemo(
    () =>
      unique([
        ...selectedPackageItems.flatMap((item) => packageNamesForOs(item, activeOs)),
        ...customPackageList
      ]),
    [activeOs, customPackageList, selectedPackageItems]
  );
  const commandSet = useMemo(
    () =>
      buildCommands({
        activeOs,
        activeTarget,
        selectedPackageNames,
        stepSelection,
        assumeYes,
        installTpm,
        dockerEnabled,
        dockerStrategy,
        nodeStrategy,
        pythonStrategy,
        javaEnabled,
        javaStrategy,
        repoRef
      }),
    [
      activeOs,
      activeTarget,
      assumeYes,
      dockerEnabled,
      dockerStrategy,
      installTpm,
      javaEnabled,
      javaStrategy,
      nodeStrategy,
      pythonStrategy,
      repoRef,
      selectedPackageNames,
      stepSelection
    ]
  );
  const configContents = useMemo(
    () =>
      Object.fromEntries(
        (Object.keys(configBlocks) as ConfigKey[]).map((key) => [key, buildConfigContent(configBlocks[key])])
      ) as Record<ConfigKey, string>,
    [configBlocks]
  );
  const dockerStrategies = useMemo(
    () => catalog.strategies.docker.filter((strategy) => strategy.id !== "none"),
    []
  );
  const nodeStrategies = useMemo(
    () => catalog.strategies.node.filter((strategy) => strategy.id !== "none"),
    []
  );
  const pythonStrategies = useMemo(
    () => catalog.strategies.python.filter((strategy) => strategy.id !== "none"),
    []
  );
  const javaStrategies = useMemo(
    () => catalog.strategies.java.filter((strategy) => strategy.id !== "none"),
    []
  );
  const selectedGroups = useMemo(
    () =>
      catalog.groups
        .map((group) => {
          const groupPackages = catalog.packages.filter((item) => item.group === group.id);
          return {
            group,
            selectedCount: groupPackages.filter((item) => selectedPackageIds.includes(item.id)).length,
            totalCount: groupPackages.length
          };
        })
        .filter((item) => item.totalCount > 0),
    [selectedPackageIds]
  );

  const switchOs = (osId: OsId) => {
    const nextDockerStrategy = defaultDockerStrategy(osId);
    setActiveOs(osId);
    setDockerEnabled(nextDockerStrategy !== "none");
    setDockerStrategy(nextDockerStrategy === "none" ? "official" : nextDockerStrategy);
  };

  const togglePackage = (packageId: string) => {
    setSelectedPackageIds((current) =>
      current.includes(packageId)
        ? current.filter((item) => item !== packageId)
        : [...current, packageId]
    );
  };

  const setGroupSelection = (groupId: string, selected: boolean) => {
    const groupPackageIds = catalog.packages
      .filter((item) => item.group === groupId)
      .map((item) => item.id);
    setSelectedPackageIds((current) => {
      if (selected) {
        return unique([...current, ...groupPackageIds]);
      }
      return current.filter((item) => !groupPackageIds.includes(item));
    });
  };

  const copyText = async (key: string, value: string) => {
    await navigator.clipboard.writeText(value);
    setCopied(key);
    window.setTimeout(() => setCopied(null), 1400);
  };

  const configCommand = buildConfigWriteCommand(configDefinitions[activeConfig], configContents[activeConfig]);
  const updateConfigBlock = (blockId: string, updater: (block: ConfigBlock) => ConfigBlock) => {
    setConfigBlocks((current) => ({
      ...current,
      [activeConfig]: current[activeConfig].map((block) => (block.id === blockId ? updater(block) : block))
    }));
  };
  const moveConfigBlock = (blockId: string, direction: -1 | 1) => {
    setConfigBlocks((current) => {
      const blocks = [...current[activeConfig]];
      const index = blocks.findIndex((block) => block.id === blockId);
      const nextIndex = index + direction;
      if (index < 0 || nextIndex < 0 || nextIndex >= blocks.length) {
        return current;
      }
      const [block] = blocks.splice(index, 1);
      blocks.splice(nextIndex, 0, block);
      return { ...current, [activeConfig]: blocks };
    });
  };
  const dropConfigBlock = (targetBlockId: string) => {
    if (!draggedBlock || draggedBlock.configKey !== activeConfig || draggedBlock.blockId === targetBlockId) {
      setDraggedBlock(null);
      return;
    }

    setConfigBlocks((current) => {
      const blocks = [...current[activeConfig]];
      const fromIndex = blocks.findIndex((block) => block.id === draggedBlock.blockId);
      const toIndex = blocks.findIndex((block) => block.id === targetBlockId);
      if (fromIndex < 0 || toIndex < 0) {
        return current;
      }
      const [block] = blocks.splice(fromIndex, 1);
      blocks.splice(toIndex, 0, block);
      return { ...current, [activeConfig]: blocks };
    });
    setDraggedBlock(null);
  };
  const resetConfigBlock = (blockId: string) => {
    const originalBlock = configDefinitions[activeConfig].blocks.find((block) => block.id === blockId);
    if (!originalBlock) {
      return;
    }
    updateConfigBlock(blockId, (block) => ({ ...block, content: originalBlock.content }));
  };

  return (
    <main className="app-shell">
      <header className="topbar">
        <div>
          <p className="section-label">goznauk/dotfiles</p>
          <h1>Build a setup plan.</h1>
        </div>
        <nav className="view-tabs" aria-label="Chooser sections">
          {(["install", "configs", "summary"] as ViewId[]).map((viewId) => (
            <button
              className={activeView === viewId ? "active" : ""}
              key={viewId}
              type="button"
              onClick={() => setActiveView(viewId)}
            >
              {viewId}
            </button>
          ))}
        </nav>
      </header>

      <TargetSelector activeOs={activeOs} activeTarget={activeTarget} onChange={switchOs} />

      {activeView === "install" && (
        <section className="main-grid">
          <div className="content-stack">
            <section className="panel">
              <div className="panel-heading">
                <div>
                  <p className="section-label">Install groups</p>
                  <h2>Choose what the command does</h2>
                </div>
              </div>
              <div className="step-grid">
                {installSteps.map((step) => (
                  <label className="option-row" key={step.key}>
                    <input
                      type="checkbox"
                      checked={stepSelection[step.key]}
                      onChange={() =>
                        setStepSelection((current) => ({
                          ...current,
                          [step.key]: !current[step.key]
                        }))
                      }
                    />
                    <span>
                      <strong>{step.title}</strong>
                      <small>{step.description}</small>
                    </span>
                  </label>
                ))}
              </div>
            </section>

            <section className="panel">
              <div className="panel-heading">
                <div>
                  <p className="section-label">Toolchains</p>
                  <h2>Containers and language runtimes</h2>
                </div>
              </div>
              <DockerStrategyControl
                activeId={dockerStrategy}
                enabled={dockerEnabled}
                onChange={(value) => setDockerStrategy(value as DockerStrategyId)}
                onEnabledChange={(enabled) => setDockerEnabled(enabled)}
                strategies={dockerStrategies}
              />
              <StrategySelector
                activeId={nodeStrategy}
                label="Node"
                onChange={(value) => setNodeStrategy(value as NodeStrategyId)}
                recommendedId="mise"
                strategies={nodeStrategies}
              />
              <StrategySelector
                activeId={pythonStrategy}
                label="Python"
                onChange={(value) => setPythonStrategy(value as PythonStrategyId)}
                recommendedId="system-uv"
                strategies={pythonStrategies}
              />
              <OptionalStrategyControl
                activeId={javaStrategy}
                disabledNote="Java runtime install is disabled. Turn it on for JVM, Gradle, or Kotlin work."
                enabled={javaEnabled}
                label="Java"
                onChange={(value) => setJavaStrategy(value as JavaStrategyId)}
                onEnabledChange={setJavaEnabled}
                recommendedId="mise-temurin-21"
                strategies={javaStrategies}
              />
            </section>

            <section className="panel">
              <div className="panel-heading package-heading">
                <div>
                  <p className="section-label">Package catalog</p>
                  <h2>{activeTarget.label} package names</h2>
                </div>
                <label className="search-field">
                  <span>Search</span>
                  <input
                    value={query}
                    onChange={(event) => setQuery(event.target.value)}
                    placeholder="package, group, or label"
                  />
                </label>
              </div>

              <div className="group-list">
                {selectedGroups.map(({ group, selectedCount, totalCount }) => (
                  <PackageGroupPanel
                    activeOs={activeOs}
                    expanded={expandedGroups[group.id] ?? false}
                    group={group}
                    key={group.id}
                    query={query}
                    selectedCount={selectedCount}
                    selectedPackageIds={selectedPackageIds}
                    totalCount={totalCount}
                    onExpand={(expanded) =>
                      setExpandedGroups((current) => ({ ...current, [group.id]: expanded }))
                    }
                    onPackageToggle={togglePackage}
                    onSelectAll={() => setGroupSelection(group.id, true)}
                    onSelectNone={() => setGroupSelection(group.id, false)}
                  />
                ))}
              </div>

              <label className="field custom-packages">
                <span>Custom {activeTarget.packageManager} packages</span>
                <input
                  value={customPackages}
                  onChange={(event) => setCustomPackages(event.target.value)}
                  placeholder="space or comma separated"
                  spellCheck={false}
                />
              </label>
            </section>
          </div>

          <CommandPanel
            activeTarget={activeTarget}
            assumeYes={assumeYes}
            commandSet={commandSet}
            copied={copied}
            dockerEnabled={dockerEnabled}
            installTpm={installTpm}
            javaEnabled={javaEnabled}
            javaStrategy={javaStrategy}
            pythonStrategy={pythonStrategy}
            repoRef={repoRef}
            selectedPackageNames={selectedPackageNames}
            setAssumeYes={setAssumeYes}
            setInstallTpm={setInstallTpm}
            setRepoRef={setRepoRef}
            onCopy={copyText}
          />
        </section>
      )}

      {activeView === "configs" && (
        <section className="main-grid">
          <div className="content-stack">
            <section className="panel">
              <div className="panel-heading">
                <div>
                  <p className="section-label">Config files</p>
                  <h2>Edit generated config content</h2>
                </div>
              </div>
              <div className="config-tabs">
                {(Object.keys(configDefinitions) as ConfigKey[]).map((key) => (
                  <button
                    className={activeConfig === key ? "active" : ""}
                    key={key}
                    type="button"
                    onClick={() => setActiveConfig(key)}
                  >
                    {configDefinitions[key].title}
                  </button>
                ))}
              </div>
              <ConfigBlockEditor
                activeBlockId={activeConfigBlockIds[activeConfig]}
                blocks={configBlocks[activeConfig]}
                configKey={activeConfig}
                draggedBlock={draggedBlock}
                generatedContent={configContents[activeConfig]}
                onActiveBlockChange={(blockId) =>
                  setActiveConfigBlockIds((current) => ({ ...current, [activeConfig]: blockId }))
                }
                onBlockContentChange={(blockId, content) =>
                  updateConfigBlock(blockId, (block) => ({ ...block, content }))
                }
                onBlockDrop={dropConfigBlock}
                onBlockMove={moveConfigBlock}
                onBlockReset={resetConfigBlock}
                onBlockToggle={(blockId) =>
                  updateConfigBlock(blockId, (block) => ({ ...block, enabled: !block.enabled }))
                }
                onDragStart={(blockId) => setDraggedBlock({ configKey: activeConfig, blockId })}
              />
            </section>
          </div>
          <aside className="panel sticky-panel">
            <p className="section-label">Config output</p>
            <h2>{configDefinitions[activeConfig].path}</h2>
            <CommandBlock
              title="Write command"
              command={configCommand}
              copied={copied === "config-command"}
              onCopy={() => copyText("config-command", configCommand)}
            />
            <button
              className="wide-button"
              type="button"
              onClick={() => copyText("config-content", configContents[activeConfig])}
            >
              {copied === "config-content" ? "Copied" : "Copy file content"}
            </button>
          </aside>
        </section>
      )}

      {activeView === "summary" && (
        <SummaryView
          activeTarget={activeTarget}
          commandSet={commandSet}
          configContents={configContents}
          dockerEnabled={dockerEnabled}
          dockerStrategy={dockerStrategy}
          javaEnabled={javaEnabled}
          javaStrategy={javaStrategy}
          nodeStrategy={nodeStrategy}
          pythonStrategy={pythonStrategy}
          selectedPackageNames={selectedPackageNames}
          stepSelection={stepSelection}
          onCopy={copyText}
          copied={copied}
        />
      )}
    </main>
  );
}

function TargetSelector({
  activeOs,
  activeTarget,
  onChange
}: {
  activeOs: OsId;
  activeTarget: OsTarget;
  onChange: (osId: OsId) => void;
}) {
  return (
    <section className="target-bar" aria-label="Operating system">
      <div>
        <p className="section-label">Target OS</p>
        <strong>{activeTarget.label}</strong>
        <span>
          {activeTarget.packageManager}
          {!activeTarget.implemented ? " preview" : ""}
        </span>
      </div>
      <div className="target-options" role="group" aria-label="Target OS choices">
        {catalog.osTargets.map((target) => (
          <button
            className={activeOs === target.id ? "target-button active" : "target-button"}
            key={target.id}
            type="button"
            onClick={() => onChange(target.id)}
          >
            <strong>{target.label}</strong>
            <span>
              {target.packageManager}
              {!target.implemented ? " preview" : ""}
            </span>
          </button>
        ))}
      </div>
    </section>
  );
}

function PackageGroupPanel({
  activeOs,
  expanded,
  group,
  query,
  selectedCount,
  selectedPackageIds,
  totalCount,
  onExpand,
  onPackageToggle,
  onSelectAll,
  onSelectNone
}: {
  activeOs: OsId;
  expanded: boolean;
  group: PackageGroup;
  query: string;
  selectedCount: number;
  selectedPackageIds: string[];
  totalCount: number;
  onExpand: (expanded: boolean) => void;
  onPackageToggle: (packageId: string) => void;
  onSelectAll: () => void;
  onSelectNone: () => void;
}) {
  const normalizedQuery = query.trim().toLowerCase();
  const packages = catalog.packages
    .filter((item) => item.group === group.id)
    .filter((item) => {
      if (!normalizedQuery) {
        return true;
      }
      const packageNames = packageNamesForOs(item, activeOs).join(" ");
      return `${group.title} ${item.label} ${item.id} ${packageNames}`
        .toLowerCase()
        .includes(normalizedQuery);
    });
  const shouldOpen = expanded || normalizedQuery.length > 0;

  if (normalizedQuery && packages.length === 0) {
    return null;
  }

  return (
    <details
      className="group-panel"
      open={shouldOpen}
      onToggle={(event) => onExpand(event.currentTarget.open)}
    >
      <summary>
        <span>
          <strong>{group.title}</strong>
          <small>{group.description}</small>
        </span>
        <em>
          {selectedCount}/{totalCount}
        </em>
      </summary>
      <div className="group-actions">
        <button type="button" onClick={onSelectAll}>
          Select group
        </button>
        <button type="button" onClick={onSelectNone}>
          Clear group
        </button>
      </div>
      <div className="package-table">
        {packages.map((item) => {
          const packageNames = packageNamesForOs(item, activeOs);
          const hasPackageForOs = packageNames.length > 0;
          return (
            <label className="package-row" key={item.id}>
              <input
                type="checkbox"
                checked={selectedPackageIds.includes(item.id)}
                disabled={!hasPackageForOs}
                onChange={() => onPackageToggle(item.id)}
              />
              <span>
                <strong>{item.label}</strong>
                <small>{hasPackageForOs ? packageNames.join(", ") : "No package needed"}</small>
                {item.note && <small>{item.note}</small>}
              </span>
            </label>
          );
        })}
      </div>
    </details>
  );
}

function StrategySelector({
  activeId,
  label,
  onChange,
  recommendedId,
  strategies
}: {
  activeId: string;
  label: string;
  onChange: (value: string) => void;
  recommendedId?: string;
  strategies: Strategy[];
}) {
  return (
    <div className="strategy-block">
      <h3>{label}</h3>
      <div className="strategy-grid">
        {strategies.map((strategy) => (
          <button
            className={activeId === strategy.id ? "strategy-card active" : "strategy-card"}
            key={strategy.id}
            type="button"
            onClick={() => onChange(strategy.id)}
          >
            <strong>
              {strategy.label}
              {strategy.id === recommendedId && <small>Recommended</small>}
            </strong>
            <span>{strategy.description}</span>
          </button>
        ))}
      </div>
    </div>
  );
}

function DockerStrategyControl({
  activeId,
  enabled,
  onChange,
  onEnabledChange,
  strategies
}: {
  activeId: DockerStrategyId;
  enabled: boolean;
  onChange: (value: string) => void;
  onEnabledChange: (enabled: boolean) => void;
  strategies: Strategy[];
}) {
  return (
    <div className="strategy-block">
      <div className="strategy-heading">
        <h3>Docker</h3>
        <label className="toggle-row">
          <input type="checkbox" checked={enabled} onChange={() => onEnabledChange(!enabled)} />
          <span>{enabled ? "On" : "Off"}</span>
        </label>
      </div>
      {enabled && (
        <div className="strategy-grid">
          {strategies.map((strategy, index) => (
            <button
              className={activeId === strategy.id ? "strategy-card active" : "strategy-card"}
              key={strategy.id}
              type="button"
              onClick={() => onChange(strategy.id)}
            >
              <strong>
                {strategy.label}
                {index === 0 && <small>Recommended</small>}
              </strong>
              <span>{strategy.description}</span>
            </button>
          ))}
        </div>
      )}
      {!enabled && (
        <p className="muted compact-note">
          Container runtime install is disabled. The generated Ubuntu command uses --docker-strategy none.
        </p>
      )}
    </div>
  );
}

function OptionalStrategyControl({
  activeId,
  disabledNote,
  enabled,
  label,
  onChange,
  onEnabledChange,
  recommendedId,
  strategies
}: {
  activeId: string;
  disabledNote: string;
  enabled: boolean;
  label: string;
  onChange: (value: string) => void;
  onEnabledChange: (enabled: boolean) => void;
  recommendedId?: string;
  strategies: Strategy[];
}) {
  return (
    <div className="strategy-block">
      <div className="strategy-heading">
        <h3>{label}</h3>
        <label className="toggle-row">
          <input type="checkbox" checked={enabled} onChange={() => onEnabledChange(!enabled)} />
          <span>{enabled ? "On" : "Off"}</span>
        </label>
      </div>
      {enabled ? (
        <div className="strategy-grid">
          {strategies.map((strategy) => (
            <button
              className={activeId === strategy.id ? "strategy-card active" : "strategy-card"}
              key={strategy.id}
              type="button"
              onClick={() => onChange(strategy.id)}
            >
              <strong>
                {strategy.label}
                {strategy.id === recommendedId && <small>Recommended</small>}
              </strong>
              <span>{strategy.description}</span>
            </button>
          ))}
        </div>
      ) : (
        <p className="muted compact-note">{disabledNote}</p>
      )}
    </div>
  );
}

function ConfigBlockEditor({
  activeBlockId,
  blocks,
  configKey,
  draggedBlock,
  generatedContent,
  onActiveBlockChange,
  onBlockContentChange,
  onBlockDrop,
  onBlockMove,
  onBlockReset,
  onBlockToggle,
  onDragStart
}: {
  activeBlockId: string;
  blocks: ConfigBlock[];
  configKey: ConfigKey;
  draggedBlock: DraggedBlock;
  generatedContent: string;
  onActiveBlockChange: (blockId: string) => void;
  onBlockContentChange: (blockId: string, content: string) => void;
  onBlockDrop: (blockId: string) => void;
  onBlockMove: (blockId: string, direction: -1 | 1) => void;
  onBlockReset: (blockId: string) => void;
  onBlockToggle: (blockId: string) => void;
  onDragStart: (blockId: string) => void;
}) {
  const activeBlock = blocks.find((block) => block.id === activeBlockId) ?? blocks[0];
  const activeIndex = blocks.findIndex((block) => block.id === activeBlock.id);
  const [selectedLine, setSelectedLine] = useState<{ blockId: string; lineIndex: number } | null>(null);
  const lineStarts = new Map<string, number>();
  let nextLineNumber = 1;

  for (const block of blocks) {
    const lineCount = block.content.trimEnd().split(/\r?\n/).length || 1;
    lineStarts.set(block.id, nextLineNumber);
    nextLineNumber += lineCount + 1;
  }

  const selectedLineBlock = selectedLine
    ? blocks.find((block) => block.id === selectedLine.blockId)
    : undefined;
  const detailLineBlock = selectedLineBlock ?? activeBlock;
  const detailLineIndex = selectedLineBlock && selectedLine ? selectedLine.lineIndex : 0;
  const selectedLineText = detailLineBlock.content.trimEnd().split(/\r?\n/)[detailLineIndex] || "";
  const selectedLineNumber = (lineStarts.get(detailLineBlock.id) ?? 1) + detailLineIndex;

  return (
    <div className="config-builder">
      <div className="config-code-pane" aria-label={`${configDefinitions[configKey].title} blocks`}>
        <div className="code-pane-header">
          <strong>{configDefinitions[configKey].title}</strong>
          <span>
            {blocks.filter((block) => block.enabled).length}/{blocks.length} blocks on
          </span>
        </div>
        {blocks.map((block, index) => (
          <div
            className={[
              "editor-block",
              block.id === activeBlock.id ? "active" : "",
              block.enabled ? "" : "disabled",
              draggedBlock?.blockId === block.id ? "dragging" : ""
            ]
              .filter(Boolean)
              .join(" ")}
            draggable
            key={block.id}
            onClick={() => onActiveBlockChange(block.id)}
            onDragOver={(event) => event.preventDefault()}
            onDragStart={() => onDragStart(block.id)}
            onDrop={() => onBlockDrop(block.id)}
          >
            <div className="editor-block-header">
              <button
                className="block-title-button"
                type="button"
                onClick={() => {
                  setSelectedLine(null);
                  onActiveBlockChange(block.id);
                }}
              >
                <span>{block.title}</span>
                <small>{block.description}</small>
              </button>
              <div className="editor-block-actions">
                <button
                  aria-label={`Move ${block.title} up`}
                  className="icon-button"
                  disabled={index === 0}
                  type="button"
                  onClick={(event) => {
                    event.stopPropagation();
                    onBlockMove(block.id, -1);
                  }}
                >
                  Up
                </button>
                <button
                  aria-label={`Move ${block.title} down`}
                  className="icon-button"
                  disabled={index === blocks.length - 1}
                  type="button"
                  onClick={(event) => {
                    event.stopPropagation();
                    onBlockMove(block.id, 1);
                  }}
                >
                  Down
                </button>
                <label className="block-toggle" onClick={(event) => event.stopPropagation()}>
                  <input type="checkbox" checked={block.enabled} onChange={() => onBlockToggle(block.id)} />
                  <span>{block.enabled ? "On" : "Off"}</span>
                </label>
              </div>
            </div>
            <div className="editor-lines">
              {(block.content.trimEnd().split(/\r?\n/) || [""]).map((line, lineIndex) => {
                const lineNumber = (lineStarts.get(block.id) ?? 1) + lineIndex;
                const lineKey = `${block.id}-${lineIndex}`;
                const lineActive = selectedLine?.blockId === block.id && selectedLine.lineIndex === lineIndex;
                return (
                  <button
                    className={lineActive ? "code-line active" : "code-line"}
                    key={lineKey}
                    type="button"
                    onClick={(event) => {
                      event.stopPropagation();
                      setSelectedLine({ blockId: block.id, lineIndex });
                      onActiveBlockChange(block.id);
                    }}
                  >
                    <span className="line-number">{lineNumber}</span>
                    <code className="line-text">{line || " "}</code>
                  </button>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      <section className="block-detail" aria-label="Selected config block">
        <div className="block-detail-heading">
          <div>
            <p className="section-label">Selected block</p>
            <h3>{activeBlock.title}</h3>
          </div>
          <span className="block-position">
            {activeIndex + 1}/{blocks.length}
          </span>
        </div>
        <p className="muted">{activeBlock.description}</p>
        {activeBlock.shortcuts.length > 0 && <KeycapList keys={activeBlock.shortcuts} />}
        <div className="selected-line-detail">
          <span>Line {selectedLineNumber}</span>
          <code>{selectedLineText || "blank line"}</code>
        </div>
        <textarea
          className="block-editor"
          spellCheck={false}
          value={activeBlock.content}
          onChange={(event) => onBlockContentChange(activeBlock.id, event.target.value)}
        />
        <div className="block-actions">
          <button type="button" onClick={() => onBlockMove(activeBlock.id, -1)} disabled={activeIndex === 0}>
            Move up
          </button>
          <button
            type="button"
            onClick={() => onBlockMove(activeBlock.id, 1)}
            disabled={activeIndex === blocks.length - 1}
          >
            Move down
          </button>
          <button type="button" onClick={() => onBlockReset(activeBlock.id)}>
            Reset block
          </button>
        </div>
        <details className="generated-config">
          <summary>Generated file text</summary>
          <textarea className="config-editor" readOnly spellCheck={false} value={generatedContent} />
        </details>
      </section>
    </div>
  );
}

function KeycapList({ keys }: { keys: string[] }) {
  return (
    <div className="keycap-list" aria-label="Keyboard shortcuts">
      {keys.map((keyName) => (
        <kbd key={keyName}>{keyName}</kbd>
      ))}
    </div>
  );
}

function CommandPanel({
  activeTarget,
  assumeYes,
  commandSet,
  copied,
  dockerEnabled,
  installTpm,
  javaEnabled,
  javaStrategy,
  pythonStrategy,
  repoRef,
  selectedPackageNames,
  setAssumeYes,
  setInstallTpm,
  setRepoRef,
  onCopy
}: {
  activeTarget: OsTarget;
  assumeYes: boolean;
  commandSet: { primary: string; local: string; packageCommand: string };
  copied: string | null;
  dockerEnabled: boolean;
  installTpm: boolean;
  javaEnabled: boolean;
  javaStrategy: JavaStrategyId;
  pythonStrategy: PythonStrategyId;
  repoRef: string;
  selectedPackageNames: string[];
  setAssumeYes: (value: boolean) => void;
  setInstallTpm: (value: boolean) => void;
  setRepoRef: (value: string) => void;
  onCopy: (key: string, value: string) => void;
}) {
  return (
    <aside className="panel sticky-panel">
      <p className="section-label">Command</p>
      <h2>{activeTarget.implemented ? "Run from terminal" : "Preview command"}</h2>
      <p className="muted">{activeTarget.note}</p>
      <label className="field">
        <span>Repository ref</span>
        <input value={repoRef} onChange={(event) => setRepoRef(event.target.value)} spellCheck={false} />
      </label>
      <label className="switch-row">
        <input type="checkbox" checked={assumeYes} onChange={() => setAssumeYes(!assumeYes)} />
        <span>Use --yes</span>
      </label>
      <label className="switch-row">
        <input type="checkbox" checked={installTpm} onChange={() => setInstallTpm(!installTpm)} />
        <span>Install TPM</span>
      </label>
      <p className="muted compact-note">Docker install: {dockerEnabled ? "on" : "off"}</p>
      <p className="muted compact-note">Python setup: {pythonStrategy}</p>
      <p className="muted compact-note">Java install: {javaEnabled ? javaStrategy : "off"}</p>
      <div className="mini-summary">
        <strong>{selectedPackageNames.length}</strong>
        <span>{activeTarget.packageManager} packages selected</span>
      </div>
      <CommandBlock
        title={activeTarget.implemented ? "Bootstrap command" : "Package command"}
        command={activeTarget.implemented ? commandSet.primary : commandSet.packageCommand}
        copied={copied === "primary-command"}
        onCopy={() =>
          onCopy("primary-command", activeTarget.implemented ? commandSet.primary : commandSet.packageCommand)
        }
      />
      {activeTarget.implemented && (
        <CommandBlock
          title="Already cloned"
          command={commandSet.local}
          copied={copied === "local-command"}
          onCopy={() => onCopy("local-command", commandSet.local)}
        />
      )}
    </aside>
  );
}

function SummaryView({
  activeTarget,
  commandSet,
  configContents,
  copied,
  dockerEnabled,
  dockerStrategy,
  javaEnabled,
  javaStrategy,
  nodeStrategy,
  pythonStrategy,
  selectedPackageNames,
  stepSelection,
  onCopy
}: {
  activeTarget: OsTarget;
  commandSet: { primary: string; local: string; packageCommand: string };
  configContents: Record<ConfigKey, string>;
  copied: string | null;
  dockerEnabled: boolean;
  dockerStrategy: DockerStrategyId;
  javaEnabled: boolean;
  javaStrategy: JavaStrategyId;
  nodeStrategy: NodeStrategyId;
  pythonStrategy: PythonStrategyId;
  selectedPackageNames: string[];
  stepSelection: Record<InstallStepKey, boolean>;
  onCopy: (key: string, value: string) => void;
}) {
  const configLineCounts = (Object.keys(configContents) as ConfigKey[]).map((key) => ({
    key,
    title: configDefinitions[key].title,
    lines: configContents[key].split(/\r?\n/).length
  }));

  return (
    <section className="summary-grid">
      <section className="panel">
        <p className="section-label">Summary</p>
        <h2>{activeTarget.label}</h2>
        <dl className="summary-list">
          <div>
            <dt>Package manager</dt>
            <dd>{activeTarget.packageManager}</dd>
          </div>
          <div>
            <dt>Install steps</dt>
            <dd>{Object.entries(stepSelection).filter(([, enabled]) => enabled).map(([key]) => key).join(", ")}</dd>
          </div>
          <div>
            <dt>Docker strategy</dt>
            <dd>{dockerEnabled ? dockerStrategy : "off"}</dd>
          </div>
          <div>
            <dt>Node strategy</dt>
            <dd>{nodeStrategy}</dd>
          </div>
          <div>
            <dt>Python strategy</dt>
            <dd>{pythonStrategy}</dd>
          </div>
          <div>
            <dt>Java strategy</dt>
            <dd>{javaEnabled ? javaStrategy : "off"}</dd>
          </div>
          <div>
            <dt>Selected packages</dt>
            <dd>{selectedPackageNames.length}</dd>
          </div>
        </dl>
      </section>
      <section className="panel">
        <p className="section-label">Packages</p>
        <h2>Resolved names</h2>
        <div className="selected-package-list">
          {selectedPackageNames.map((name) => (
            <span key={name}>{name}</span>
          ))}
        </div>
      </section>
      <section className="panel">
        <p className="section-label">Configs</p>
        <h2>Editable files</h2>
        <ul className="plain-list">
          {configLineCounts.map((item) => (
            <li key={item.key}>
              {item.title}: {item.lines} lines
            </li>
          ))}
        </ul>
      </section>
      <section className="panel command-summary">
        <p className="section-label">Final command</p>
        <CommandBlock
          title={activeTarget.implemented ? "Bootstrap command" : "Package command"}
          command={activeTarget.implemented ? commandSet.primary : commandSet.packageCommand}
          copied={copied === "summary-command"}
          onCopy={() =>
            onCopy("summary-command", activeTarget.implemented ? commandSet.primary : commandSet.packageCommand)
          }
        />
      </section>
    </section>
  );
}

type BuildCommandInput = {
  activeOs: OsId;
  activeTarget: OsTarget;
  selectedPackageNames: string[];
  stepSelection: Record<InstallStepKey, boolean>;
  assumeYes: boolean;
  installTpm: boolean;
  dockerEnabled: boolean;
  dockerStrategy: DockerStrategyId;
  nodeStrategy: NodeStrategyId;
  pythonStrategy: PythonStrategyId;
  javaEnabled: boolean;
  javaStrategy: JavaStrategyId;
  repoRef: string;
};

function buildCommands(input: BuildCommandInput) {
  const activeRef = input.repoRef.trim() || DEFAULT_REF;
  const flags: string[] = [];

  if (input.assumeYes) {
    flags.push("--yes");
  }

  for (const step of installSteps) {
    if (!input.stepSelection[step.key]) {
      flags.push(step.skipFlag);
    }
  }

  if (input.stepSelection.packages) {
    if (input.selectedPackageNames.length > 0) {
      flags.push("--apt-packages", input.selectedPackageNames.join(","));
    } else {
      flags.push("--skip-apt");
    }
    flags.push("--docker-strategy", input.dockerEnabled ? input.dockerStrategy : "none");
  }

  if (input.stepSelection.tools) {
    flags.push("--node-strategy", input.nodeStrategy);
    flags.push("--python-strategy", input.pythonStrategy);
    flags.push("--java-strategy", input.javaEnabled ? input.javaStrategy : "none");
  }

  if (input.installTpm) {
    flags.push("--with-tpm");
  }

  const setupArgs = [input.activeTarget.commandTarget, ...flags].map(shellQuote).join(" ");
  const envPrefix = activeRef === DEFAULT_REF ? "" : `DOTFILES_REPO_REF=${shellQuote(activeRef)} `;
  const url = `https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${activeRef}/install.sh`;

  return {
    primary: `curl -fsSL ${shellQuote(url)} | ${envPrefix}bash -s -- ${setupArgs}`,
    local: `./setup.sh ${setupArgs}`,
    packageCommand: buildPackageCommand(
      input.activeOs,
      input.selectedPackageNames,
      input.dockerEnabled ? input.dockerStrategy : "none",
      input.nodeStrategy,
      input.pythonStrategy,
      input.javaEnabled ? input.javaStrategy : "none"
    )
  };
}

function buildPackageCommand(
  osId: OsId,
  packages: string[],
  dockerStrategy: DockerStrategyId,
  nodeStrategy: NodeStrategyId,
  pythonStrategy: PythonStrategyId,
  javaStrategy: JavaStrategyId
) {
  const installLine =
    osId === "macos"
      ? packages.length > 0
        ? `brew install ${packages.map(shellQuote).join(" ")}`
        : "# No brew packages selected"
      : packages.length > 0
        ? `sudo dnf install -y ${packages.map(shellQuote).join(" ")}`
        : "# No dnf packages selected";
  const dockerLine = dockerPreviewLine(osId, dockerStrategy);
  const nodeLine = nodePreviewLine(nodeStrategy);
  const pythonLine = pythonPreviewLine(pythonStrategy);
  const javaLine = javaPreviewLine(osId, javaStrategy);

  return [installLine, dockerLine, nodeLine, pythonLine, javaLine].filter(Boolean).join("\n");
}

function dockerPreviewLine(osId: OsId, strategy: DockerStrategyId) {
  if (strategy === "none") {
    return "# Container runtime skipped";
  }
  if (osId === "macos") {
    return strategy === "official" || strategy === "distro"
      ? "brew install --cask docker"
      : "# Podman on macOS usually needs podman machine setup";
  }
  if (strategy === "podman") {
    return "sudo dnf install -y podman podman-docker";
  }
  if (strategy === "distro") {
    return "sudo dnf install -y docker";
  }
  return "# Use Docker official repository instructions for this OS";
}

function nodePreviewLine(strategy: NodeStrategyId) {
  if (strategy === "none") {
    return "# Node setup skipped";
  }
  if (strategy === "nvm") {
    return "curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash";
  }
  return "curl -fsSL https://mise.run | sh && mise use -g node@lts";
}

function pythonPreviewLine(strategy: PythonStrategyId) {
  if (strategy === "none") {
    return "# Extra Python runtime setup skipped";
  }
  if (strategy === "mise") {
    return "curl -fsSL https://mise.run | sh && mise use -g python@latest";
  }
  return "curl -LsSf https://astral.sh/uv/install.sh | sh";
}

function javaPreviewLine(osId: OsId, strategy: JavaStrategyId) {
  if (strategy === "none") {
    return "# Java setup skipped";
  }
  if (strategy === "mise-temurin-21") {
    return "curl -fsSL https://mise.run | sh && mise use -g java@temurin-21";
  }
  if (osId === "macos") {
    return "brew install openjdk@21";
  }
  return osId === "ubuntu" ? "sudo apt install -y openjdk-21-jdk" : "sudo dnf install -y java-21-openjdk-devel";
}

function buildConfigWriteCommand(
  definition: { path: string; mkdir?: string },
  content: string
) {
  const mkdirLine = definition.mkdir ? `mkdir -p ${definition.mkdir}\n` : "";
  return `${mkdirLine}cat > ${definition.path} <<'EOF'\n${content.replace(/\n?$/, "\n")}EOF`;
}

type CommandBlockProps = {
  title: string;
  command: string;
  copied: boolean;
  onCopy: () => void;
};

function CommandBlock({ title, command, copied, onCopy }: CommandBlockProps) {
  return (
    <div className="command-block">
      <div className="command-header">
        <h3>{title}</h3>
        <button type="button" onClick={onCopy}>
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
      <pre>
        <code>{command}</code>
      </pre>
    </div>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
