import { StrictMode, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import catalogData from "../../packages/catalog.json";
import tmuxConfigRaw from "../../common/.tmux.conf?raw";
import vimConfigRaw from "../../common/.vimrc?raw";
import zshConfigRaw from "../../common/.zshrc?raw";
import {
  DEFAULT_REF,
  buildCommands,
  buildConfigWriteCommand,
  installSteps,
  type CommandSet
} from "./commandBuilder";
import "./styles.css";

type OsId = "ubuntu" | "macos" | "amazon" | "rhel";
type ViewId = "target" | "packages" | "toolchains" | "configs" | "summary";
type ThemeMode = "light" | "dark";
type InstallStepKey = "packages" | "shell" | "dotfiles" | "tools";
type DockerStrategyId = "official" | "distro" | "podman" | "none";
type NodeStrategyId = "mise" | "nvm" | "none";
type PythonStrategyId = "system-uv" | "mise" | "none";
type JavaStrategyId = "mise-temurin-21" | "distro-openjdk-21" | "none";
type ConfigKey = "zshrc" | "vimrc" | "tmux" | "htop";
type ConfigBlockKind = "locked" | "ordered" | "side-effect" | "free";
type DraggedBlock = { configKey: ConfigKey; blockId: string } | null;

type OsVersion = {
  value: string;
  label: string;
  note: string;
};

type OsTarget = {
  id: OsId;
  label: string;
  packageManager: string;
  commandTarget: string;
  implemented: boolean;
  note: string;
  defaultVersion: string;
  versions: OsVersion[];
};

type PackageGroup = {
  id: string;
  title: string;
  description: string;
  defaultEnabled: boolean;
};

type CatalogPackage = {
  id: string;
  group: string;
  label: string;
  defaultSelected: boolean;
  packages: Record<OsId, string[]>;
  note?: string;
};

type Strategy = {
  id: string;
  label: string;
  description: string;
  defaults?: OsId[];
};

type ConfigBlock = {
  id: string;
  title: string;
  description: string;
  kind: ConfigBlockKind;
  shortcuts: string[];
  risk?: string;
  enabled: boolean;
  content: string;
};

type ConfigBlockTemplate = Omit<ConfigBlock, "enabled" | "content" | "kind"> & {
  start: number;
  end: number;
  kind?: ConfigBlockKind;
  enabled?: boolean;
};

type Catalog = {
  osTargets: OsTarget[];
  groups: PackageGroup[];
  packages: CatalogPackage[];
  strategies: {
    docker: Strategy[];
    node: Strategy[];
    python: Strategy[];
    java: Strategy[];
  };
};

const catalog = catalogData as Catalog;

const htopConfigDefault = `# htop config generated by dotfiles chooser
fields=0 48 17 18 38 39 2 46 47 49 1
sort_key=46
sort_direction=1
tree_sort_key=0
tree_sort_direction=1
hide_kernel_threads=1
hide_userland_threads=0
shadow_other_users=0
show_thread_names=0
show_program_path=1
highlight_base_name=1
highlight_megabytes=1
highlight_threads=1
highlight_changes=0
highlight_changes_delay_secs=5
find_comm_in_cmdline=1
strip_exe_from_cmdline=1
show_merged_command=0
header_margin=1
detailed_cpu_time=0
cpu_count_from_one=0
show_cpu_usage=1
show_cpu_frequency=1
show_cpu_temperature=0
degree_fahrenheit=0
update_process_names=0
account_guest_in_cpu_meter=0
color_scheme=0
enable_mouse=1
delay=15
left_meters=LeftCPUs2 Memory Swap
left_meter_modes=1 1 1
right_meters=RightCPUs2 Tasks LoadAverage Uptime
right_meter_modes=1 2 2 2
`;

const createConfigBlocks = (raw: string, templates: ConfigBlockTemplate[]): ConfigBlock[] => {
  const lines = raw.trimEnd().split(/\r?\n/);
  return templates.map((template) => ({
    id: template.id,
    title: template.title,
    description: template.description,
    kind: template.kind ?? "free",
    shortcuts: template.shortcuts,
    risk: template.risk,
    enabled: template.enabled ?? true,
    content: `${lines.slice(template.start - 1, template.end).join("\n")}\n`
  }));
};

const blockKindLabels: Record<ConfigBlockKind, string> = {
  locked: "Locked order",
  ordered: "Order matters",
  "side-effect": "Side effect",
  free: "Safe to move"
};

const blockKindDescriptions: Record<ConfigBlockKind, string> = {
  locked: "Keep this block in place unless you are deliberately changing startup order.",
  ordered: "This block can be edited, but it depends on nearby setup happening first.",
  "side-effect": "This block can run external tools, create files, or load plugin managers.",
  free: "This block is mostly aliases, display settings, or local preferences."
};

const configDefinitions: Record<
  ConfigKey,
  { title: string; path: string; mkdir?: string; blocks: ConfigBlock[] }
> = {
  zshrc: {
    title: ".zshrc",
    path: "$HOME/.zshrc",
    blocks: createConfigBlocks(zshConfigRaw, [
      {
        id: "interactive-guard",
        title: "Interactive guard",
        description: "Stops non-interactive shells from loading prompt and alias setup, then loads the pre-hook.",
        kind: "locked",
        risk: "Keep this first. Moving it can make scripts inherit interactive shell behavior.",
        shortcuts: [],
        start: 1,
        end: 3
      },
      {
        id: "prompt",
        title: "Prompt bootstrap",
        description: "Loads the Powerlevel10k instant prompt and selects the prompt theme.",
        kind: "locked",
        risk: "Keep this near the top. Moving it below other shell output can break instant prompt startup.",
        shortcuts: [],
        start: 5,
        end: 16
      },
      {
        id: "history",
        title: "History settings",
        description: "Keeps a large shared history and avoids repeated duplicate commands.",
        kind: "free",
        shortcuts: [],
        start: 18,
        end: 28
      },
      {
        id: "path",
        title: "PATH order",
        description: "Puts local user tools, Cargo tools, and home bin ahead of system paths.",
        kind: "ordered",
        risk: "Keep this before plugin and runtime setup so command checks resolve the expected tools.",
        shortcuts: [],
        start: 30,
        end: 41
      },
      {
        id: "plugins",
        title: "oh-my-zsh plugins",
        description: "Enables Git helpers, dotenv loading, completions, suggestions, and Docker helpers when Docker exists.",
        kind: "ordered",
        risk: "Keep this before oh-my-zsh loads. Plugins listed after the framework block will not load.",
        shortcuts: [],
        start: 43,
        end: 51
      },
      {
        id: "framework",
        title: "Shell framework",
        description: "Loads oh-my-zsh when available and falls back to plain completion setup.",
        kind: "locked",
        risk: "Runtime hooks, aliases, and plugin arrays assume this framework block stays before them.",
        shortcuts: [],
        start: 53,
        end: 61
      },
      {
        id: "runtime-hooks",
        title: "Runtime hooks",
        description: "Activates mise and direnv in interactive shells when those tools exist.",
        kind: "side-effect",
        risk: "Keep this after PATH setup so mise and direnv are discovered from the expected locations.",
        shortcuts: [],
        start: 63,
        end: 69
      },
      {
        id: "environment",
        title: "Environment",
        description: "Sets locale, editor, visual editor, and GPG tty defaults without overriding existing values.",
        kind: "free",
        shortcuts: [],
        start: 71,
        end: 77
      },
      {
        id: "history-search",
        title: "History search keys",
        description: "Makes Up and Down search matching command history from the current prefix.",
        kind: "free",
        shortcuts: ["Up", "Down"],
        start: 79,
        end: 83
      },
      {
        id: "safe-aliases",
        title: "Prompted aliases",
        description: "Keeps raw rm, cp, and mv untouched, and adds explicit prompted variants.",
        kind: "free",
        shortcuts: ["rmi", "rmri", "cpi", "mvi"],
        start: 85,
        end: 90
      },
      {
        id: "navigation",
        title: "Navigation and listings",
        description: "Adds short directory and listing aliases used during terminal work.",
        kind: "free",
        shortcuts: ["cd..", "l", "ll", "la"],
        start: 92,
        end: 97
      },
      {
        id: "tmux-docker",
        title: "tmux and Docker aliases",
        description: "Adds the session attach flow and common Docker Compose shortcuts.",
        kind: "free",
        shortcuts: ["ta 0", "ta0", "tls", "tn"],
        start: 99,
        end: 105
      },
      {
        id: "editors",
        title: "Edit helpers",
        description: "Adds quick commands for editing and applying the shell configuration.",
        kind: "free",
        shortcuts: ["zshrc", "zshrc_apply"],
        start: 107,
        end: 108
      },
      {
        id: "inspection",
        title: "Inspection helpers",
        description: "Adds compact helpers for listening ports, IP addresses, and PATH entries.",
        kind: "free",
        shortcuts: ["ports", "ipb", "pathls"],
        start: 110,
        end: 124
      },
      {
        id: "local-prompt",
        title: "Local hooks and prompt file",
        description: "Loads local customizations and then the generated Powerlevel10k prompt file.",
        kind: "locked",
        risk: "Keep this at the end so local overrides and prompt config apply after framework setup.",
        shortcuts: [],
        start: 126,
        end: 127
      }
    ])
  },
  vimrc: {
    title: ".vimrc",
    path: "$HOME/.vimrc",
    blocks: createConfigBlocks(vimConfigRaw, [
      {
        id: "core",
        title: "Core mode",
        description: "Starts Vim in modern mode with filetype plugins, indentation, syntax, and a space leader.",
        kind: "locked",
        shortcuts: [],
        start: 1,
        end: 4
      },
      {
        id: "encoding",
        title: "Encoding and files",
        description: "Sets UTF-8 defaults, safer bells, autoread, hidden buffers, swap, undo, and cache directories.",
        kind: "side-effect",
        risk: "This creates ~/.vim cache directories during startup so project directories stay clean.",
        shortcuts: [],
        start: 6,
        end: 21
      },
      {
        id: "indent",
        title: "Indentation",
        description: "Uses two-space indentation by default with expanded tabs.",
        kind: "free",
        shortcuts: [],
        start: 23,
        end: 29
      },
      {
        id: "search",
        title: "Search behavior",
        description: "Enables incremental smart-case search and a quick mapping to clear highlights.",
        kind: "free",
        shortcuts: ["leader", "Space"],
        start: 31,
        end: 35
      },
      {
        id: "performance",
        title: "Completion and redraw",
        description: "Keeps completion local and avoids unnecessary redraw work.",
        kind: "free",
        shortcuts: [],
        start: 37,
        end: 39
      },
      {
        id: "interface",
        title: "Interface",
        description: "Shows status, ruler, line numbers, command feedback, title, mouse, colors, and split direction.",
        kind: "free",
        shortcuts: [],
        start: 41,
        end: 53
      },
      {
        id: "plugins",
        title: "vim-plug setup",
        description: "Uses vim-plug only when plug.vim exists, with vim-sensible and EditorConfig support.",
        kind: "side-effect",
        risk: "Keep plugin declarations after core Vim settings and before filetype-specific overrides.",
        shortcuts: [":PlugInstall"],
        start: 55,
        end: 61
      },
      {
        id: "filetypes",
        title: "Filetype indentation",
        description: "Overrides indentation for common web, Ruby, and Python files.",
        kind: "ordered",
        risk: "Keep the augroup together so sourcing .vimrc replaces old autocmds instead of duplicating them.",
        shortcuts: [],
        start: 63,
        end: 69
      }
    ])
  },
  tmux: {
    title: ".tmux.conf",
    path: "$HOME/.tmux.conf",
    blocks: createConfigBlocks(tmuxConfigRaw, [
      {
        id: "prefix",
        title: "Prefix and reload",
        description: "Uses Ctrl-A as the prefix and binds reload to prefix plus r.",
        kind: "locked",
        risk: "Keep prefix bindings before later key bindings so the rest of the file uses the expected prefix.",
        shortcuts: ["C-a", "C-a r"],
        start: 1,
        end: 6
      },
      {
        id: "terminal",
        title: "Terminal capabilities",
        description: "Sets tmux-256color and truecolor capability hints for modern terminals.",
        kind: "ordered",
        risk: "Keep this before status and color styling so later color settings render correctly.",
        shortcuts: [],
        start: 8,
        end: 10
      },
      {
        id: "session",
        title: "Session behavior",
        description: "Enables mouse support, focus events, clipboard, renumbering, and deep history.",
        kind: "free",
        shortcuts: [],
        start: 12,
        end: 19
      },
      {
        id: "indexes",
        title: "Indexes",
        description: "Starts windows and panes at 1 for easier keyboard targeting.",
        kind: "ordered",
        risk: "Move this only if every window and pane binding still expects one-based indexes.",
        shortcuts: ["1"],
        start: 21,
        end: 23
      },
      {
        id: "windows",
        title: "Windows and panes",
        description: "Adds pane splits, vim-style pane movement, window navigation, and resize keys.",
        kind: "free",
        shortcuts: ["c", "|", "-", "h", "j", "k", "l", "Tab"],
        start: 25,
        end: 42
      },
      {
        id: "copy",
        title: "Copy mode",
        description: "Uses vi copy mode and tries macOS and Linux clipboard tools before falling back.",
        kind: "side-effect",
        risk: "Keep mode-keys before copy bindings. Clipboard commands run when text is copied.",
        shortcuts: ["v", "y", "Enter"],
        start: 44,
        end: 49
      },
      {
        id: "status",
        title: "Status line",
        description: "Sets a compact status line with host, session, date, time, window, and pane.",
        kind: "free",
        shortcuts: [],
        start: 51,
        end: 63
      },
      {
        id: "tpm",
        title: "TPM block",
        description: "Keeps the tmux plugin manager block available but commented by default.",
        kind: "side-effect",
        risk: "Keep TPM plugin declarations near the bottom. TPM expects plugin lines before its run command.",
        shortcuts: ["prefix", "I"],
        start: 65,
        end: 69
      }
    ])
  },
  htop: {
    title: "htoprc",
    path: "$HOME/.config/htop/htoprc",
    mkdir: "$HOME/.config/htop",
    blocks: createConfigBlocks(htopConfigDefault, [
      {
        id: "columns",
        title: "Columns and sorting",
        description: "Chooses the visible process columns and sorts by memory usage.",
        shortcuts: ["F6"],
        start: 1,
        end: 5
      },
      {
        id: "visibility",
        title: "Visibility",
        description: "Controls thread display, merged commands, highlighting, and path behavior.",
        shortcuts: ["H", "K"],
        start: 6,
        end: 24
      },
      {
        id: "runtime",
        title: "Runtime display",
        description: "Sets color scheme, mouse support, refresh delay, and CPU display behavior.",
        shortcuts: ["F2", "F9"],
        start: 25,
        end: 31
      },
      {
        id: "meters",
        title: "Header meters",
        description: "Shows CPU, memory, swap, task, load, and uptime meters.",
        shortcuts: [],
        start: 32,
        end: 35
      }
    ])
  }
};

const createInitialConfigBlocks = () =>
  Object.fromEntries(
    (Object.keys(configDefinitions) as ConfigKey[]).map((key) => [
      key,
      configDefinitions[key].blocks.map((block) => ({ ...block }))
    ])
  ) as Record<ConfigKey, ConfigBlock[]>;

const createInitialActiveBlocks = () =>
  Object.fromEntries(
    (Object.keys(configDefinitions) as ConfigKey[]).map((key) => [key, configDefinitions[key].blocks[0].id])
  ) as Record<ConfigKey, string>;

const buildConfigContent = (blocks: ConfigBlock[]) =>
  blocks
    .filter((block) => block.enabled)
    .map((block) => block.content.trimEnd())
    .filter(Boolean)
    .join("\n\n")
    .concat("\n");

const splitCustomPackages = (value: string) =>
  value
    .split(/[,\s]+/)
    .map((item) => item.trim())
    .filter(Boolean);

const unique = (items: string[]) => Array.from(new Set(items.filter(Boolean)));

const defaultDockerStrategy = (osId: OsId): DockerStrategyId => {
  const strategy = catalog.strategies.docker.find((item) => item.defaults?.includes(osId));
  return (strategy?.id as DockerStrategyId | undefined) ?? "none";
};

const defaultVersionForTarget = (target: OsTarget) =>
  target.defaultVersion || target.versions[0]?.value || "";

const targetShortLabel = (target: OsTarget) => (target.id === "amazon" ? "AL2023" : target.label);

const createInitialTargetVersions = () =>
  Object.fromEntries(
    catalog.osTargets.map((target) => [target.id, defaultVersionForTarget(target)])
  ) as Record<OsId, string>;

const packageNamesForOs = (item: CatalogPackage, osId: OsId) => item.packages[osId] ?? [];

const packageDescriptionFor = (item: CatalogPackage, group: PackageGroup) =>
  item.note ?? group.description;

const initialParams =
  typeof window === "undefined" ? new URLSearchParams() : new URLSearchParams(window.location.search);

const readInitialTheme = (): ThemeMode => {
  if (typeof window === "undefined") {
    return "light";
  }
  const queryTheme = initialParams.get("theme");
  if (queryTheme === "light" || queryTheme === "dark") {
    return queryTheme;
  }
  try {
    const stored = window.localStorage.getItem("dotfiles-theme");
    if (stored === "light" || stored === "dark") {
      return stored;
    }
  } catch {
    return "light";
  }
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
};

const readInitialView = (): ViewId => {
  const view = initialParams.get("view");
  if (view === "install") {
    return "target";
  }
  return view === "target" ||
    view === "packages" ||
    view === "toolchains" ||
    view === "configs" ||
    view === "summary"
    ? view
    : "target";
};

const readInitialOs = (): OsId => {
  const os = initialParams.get("os");
  return catalog.osTargets.some((target) => target.id === os) ? (os as OsId) : "ubuntu";
};

const readInitialConfig = (): ConfigKey => {
  const config = initialParams.get("config");
  return config === "vimrc" || config === "tmux" || config === "htop" || config === "zshrc"
    ? config
    : "zshrc";
};

const readInitialExpandedGroups = () => {
  const groups = new Set(
    initialParams
      .getAll("group")
      .flatMap((value) => value.split(","))
      .map((value) => value.trim())
      .filter(Boolean)
  );

  return Object.fromEntries(catalog.groups.map((group) => [group.id, groups.has(group.id)]));
};

const sectionAnchorId = (viewId: ViewId) => `${viewId}-section`;
const sectionNavItems: Array<{ id: ViewId; label: string }> = [
  { id: "target", label: "Target" },
  { id: "packages", label: "Packages" },
  { id: "toolchains", label: "Toolchains" },
  { id: "configs", label: "Config" },
  { id: "summary", label: "Run" }
];

const scrollSectionIntoView = (viewId: ViewId, behavior: ScrollBehavior = "smooth") => {
  const section = document.getElementById(sectionAnchorId(viewId));
  if (!section) {
    return false;
  }

  if (typeof section.scrollIntoView === "function") {
    section.scrollIntoView({ behavior, block: "start" });
    return true;
  }

  const anchor = `#${sectionAnchorId(viewId)}`;
  if (window.location.hash !== anchor) {
    window.location.hash = anchor;
  }
  return true;
};

function App() {
  const initialOs = readInitialOs();
  const initialView = readInitialView();
  const [activeView, setActiveView] = useState<ViewId>(initialView);
  const [themeMode, setThemeMode] = useState<ThemeMode>(readInitialTheme);
  const [activeOs, setActiveOs] = useState<OsId>(initialOs);
  const [targetSelected, setTargetSelected] = useState(() => initialParams.has("os") || initialView !== "target");
  const [targetVersions, setTargetVersions] = useState<Record<OsId, string>>(createInitialTargetVersions);
  const [selectedPackageIds, setSelectedPackageIds] = useState<string[]>(
    catalog.packages.filter((item) => item.defaultSelected).map((item) => item.id)
  );
  const [expandedGroups, setExpandedGroups] = useState<Record<string, boolean>>(
    readInitialExpandedGroups
  );
  const [stepSelection, setStepSelection] = useState<Record<InstallStepKey, boolean>>({
    packages: true,
    shell: true,
    dotfiles: true,
    tools: true
  });
  const [query, setQuery] = useState("");
  const [customPackages, setCustomPackages] = useState("");
  const [dockerStrategy, setDockerStrategy] = useState<DockerStrategyId>(() => {
    const strategy = defaultDockerStrategy(initialOs);
    return strategy === "none" ? "official" : strategy;
  });
  const [dockerEnabled, setDockerEnabled] = useState(
    initialParams.get("docker") === "off" ? false : defaultDockerStrategy(initialOs) !== "none"
  );
  const [nodeStrategy, setNodeStrategy] = useState<NodeStrategyId>("mise");
  const [nodeEnabled, setNodeEnabled] = useState(true);
  const [pythonStrategy, setPythonStrategy] = useState<PythonStrategyId>("system-uv");
  const [pythonEnabled, setPythonEnabled] = useState(true);
  const [javaStrategy, setJavaStrategy] = useState<JavaStrategyId>("mise-temurin-21");
  const [javaEnabled, setJavaEnabled] = useState(false);
  const [installTpm, setInstallTpm] = useState(false);
  const [powerlevel10k, setPowerlevel10k] = useState(true);
  const [prepareSystem, setPrepareSystem] = useState(true);
  const [runInTmux, setRunInTmux] = useState(true);
  const [assumeYes, setAssumeYes] = useState(true);
  const [repoRef, setRepoRef] = useState(DEFAULT_REF);
  const [copied, setCopied] = useState<string | null>(null);
  const [copyError, setCopyError] = useState<string | null>(null);
  const [activeConfig, setActiveConfig] = useState<ConfigKey>(readInitialConfig);
  const [configBlocks, setConfigBlocks] = useState<Record<ConfigKey, ConfigBlock[]>>(createInitialConfigBlocks);
  const [activeConfigBlockIds, setActiveConfigBlockIds] =
    useState<Record<ConfigKey, string>>(createInitialActiveBlocks);
  const [draggedBlock, setDraggedBlock] = useState<DraggedBlock>(null);

  useEffect(() => {
    document.documentElement.dataset.theme = themeMode;
    document.documentElement.style.colorScheme = themeMode;
    try {
      window.localStorage.setItem("dotfiles-theme", themeMode);
    } catch {
      // Ignore private browsing or blocked storage.
    }
  }, [themeMode]);

  useEffect(() => {
    const sections = sectionNavItems.map((item) => item.id);
    const updateActiveView = () => {
      let currentView: ViewId = "target";
      for (const viewId of sections) {
        const section = document.getElementById(sectionAnchorId(viewId));
        if (section && section.getBoundingClientRect().top <= 128) {
          currentView = viewId;
        }
      }
      setActiveView(currentView);
    };

    window.addEventListener("scroll", updateActiveView, { passive: true });
    window.setTimeout(() => {
      if (initialView !== "target" && scrollSectionIntoView(initialView, "auto")) {
        updateActiveView();
      } else {
        updateActiveView();
      }
    }, 0);

    return () => window.removeEventListener("scroll", updateActiveView);
  }, [initialView]);

  const activeTarget = catalog.osTargets.find((target) => target.id === activeOs) ?? catalog.osTargets[0];
  const activeTargetVersion = targetVersions[activeOs] ?? defaultVersionForTarget(activeTarget);
  const selectedPackageItems = useMemo(
    () => catalog.packages.filter((item) => selectedPackageIds.includes(item.id)),
    [selectedPackageIds]
  );
  const customPackageList = useMemo(() => splitCustomPackages(customPackages), [customPackages]);
  const selectedPackageNames = useMemo(
    () =>
      unique([
        ...selectedPackageItems.flatMap((item) => packageNamesForOs(item, activeOs)),
        ...customPackageList
      ]),
    [activeOs, customPackageList, selectedPackageItems]
  );
  const commandSet = useMemo(
    () =>
      buildCommands({
        activeOs,
        activeTarget,
        targetVersion: activeTargetVersion,
        selectedPackageNames,
        stepSelection,
        assumeYes,
        installTpm,
        dockerEnabled,
        dockerStrategy,
        nodeStrategy: nodeEnabled ? nodeStrategy : "none",
        pythonStrategy: pythonEnabled ? pythonStrategy : "none",
        javaEnabled,
        javaStrategy,
        powerlevel10k,
        prepareSystem,
        runInTmux,
        repoRef
      }),
    [
      activeOs,
      activeTarget,
      activeTargetVersion,
      assumeYes,
      dockerEnabled,
      dockerStrategy,
      installTpm,
      javaEnabled,
      javaStrategy,
      nodeEnabled,
      nodeStrategy,
      powerlevel10k,
      prepareSystem,
      pythonEnabled,
      pythonStrategy,
      repoRef,
      runInTmux,
      selectedPackageNames,
      stepSelection
    ]
  );
  const configContents = useMemo(
    () =>
      Object.fromEntries(
        (Object.keys(configBlocks) as ConfigKey[]).map((key) => [key, buildConfigContent(configBlocks[key])])
      ) as Record<ConfigKey, string>,
    [configBlocks]
  );
  const dockerStrategies = useMemo(
    () => catalog.strategies.docker.filter((strategy) => strategy.id !== "none"),
    []
  );
  const nodeStrategies = useMemo(
    () => catalog.strategies.node.filter((strategy) => strategy.id !== "none"),
    []
  );
  const pythonStrategies = useMemo(
    () => catalog.strategies.python.filter((strategy) => strategy.id !== "none"),
    []
  );
  const javaStrategies = useMemo(
    () => catalog.strategies.java.filter((strategy) => strategy.id !== "none"),
    []
  );
  const selectedGroups = useMemo(
    () =>
      catalog.groups
        .map((group) => {
          const groupPackages = catalog.packages.filter((item) => item.group === group.id);
          return {
            group,
            selectedCount: groupPackages.filter((item) => selectedPackageIds.includes(item.id)).length,
            totalCount: groupPackages.length
          };
        })
        .filter((item) => item.totalCount > 0),
    [selectedPackageIds]
  );

  const switchOs = (osId: OsId) => {
    const nextDockerStrategy = defaultDockerStrategy(osId);
    setActiveOs(osId);
    setDockerEnabled(nextDockerStrategy !== "none");
    setDockerStrategy(nextDockerStrategy === "none" ? "official" : nextDockerStrategy);
  };

  const togglePackage = (packageId: string) => {
    setSelectedPackageIds((current) =>
      current.includes(packageId)
        ? current.filter((item) => item !== packageId)
        : [...current, packageId]
    );
  };

  const setGroupSelection = (groupId: string, selected: boolean) => {
    const groupPackageIds = catalog.packages
      .filter((item) => item.group === groupId)
      .map((item) => item.id);
    setSelectedPackageIds((current) => {
      if (selected) {
        return unique([...current, ...groupPackageIds]);
      }
      return current.filter((item) => !groupPackageIds.includes(item));
    });
  };

  const copyText = async (key: string, value: string) => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(key);
      setCopyError(null);
      window.setTimeout(() => setCopied(null), 1400);
    } catch {
      setCopied(null);
      setCopyError("Copy failed. Select the command text and copy it manually.");
      window.setTimeout(() => setCopyError(null), 5000);
    }
  };

  const configCommand = buildConfigWriteCommand(configDefinitions[activeConfig], configContents[activeConfig]);
  const updateConfigBlock = (blockId: string, updater: (block: ConfigBlock) => ConfigBlock) => {
    setConfigBlocks((current) => ({
      ...current,
      [activeConfig]: current[activeConfig].map((block) => (block.id === blockId ? updater(block) : block))
    }));
  };
  const moveConfigBlock = (blockId: string, direction: -1 | 1) => {
    setConfigBlocks((current) => {
      const blocks = [...current[activeConfig]];
      const index = blocks.findIndex((block) => block.id === blockId);
      const nextIndex = index + direction;
      if (index < 0 || nextIndex < 0 || nextIndex >= blocks.length) {
        return current;
      }
      const [block] = blocks.splice(index, 1);
      blocks.splice(nextIndex, 0, block);
      return { ...current, [activeConfig]: blocks };
    });
  };
  const dropConfigBlock = (targetBlockId: string) => {
    if (!draggedBlock || draggedBlock.configKey !== activeConfig || draggedBlock.blockId === targetBlockId) {
      setDraggedBlock(null);
      return;
    }

    setConfigBlocks((current) => {
      const blocks = [...current[activeConfig]];
      const fromIndex = blocks.findIndex((block) => block.id === draggedBlock.blockId);
      const toIndex = blocks.findIndex((block) => block.id === targetBlockId);
      if (fromIndex < 0 || toIndex < 0) {
        return current;
      }
      const [block] = blocks.splice(fromIndex, 1);
      blocks.splice(toIndex, 0, block);
      return { ...current, [activeConfig]: blocks };
    });
    setDraggedBlock(null);
  };
  const resetConfigBlock = (blockId: string) => {
    const originalBlock = configDefinitions[activeConfig].blocks.find((block) => block.id === blockId);
    if (!originalBlock) {
      return;
    }
    updateConfigBlock(blockId, (block) => ({ ...block, content: originalBlock.content }));
  };

  return (
    <main className="app-shell">
      <header className="topbar">
        <div>
          <p className="section-label">goznauk/dotfiles</p>
          <h1>Build a setup plan.</h1>
        </div>
        <div className="topbar-actions">
          <ThemeToggle mode={themeMode} onChange={setThemeMode} />
        </div>
      </header>

      <nav className="view-tabs sticky-tabs" aria-label="Chooser sections">
        {sectionNavItems.map((item) => (
          <a
            className={activeView === item.id ? "active" : ""}
            href={`#${sectionAnchorId(item.id)}`}
            key={item.id}
            onClick={() => setActiveView(item.id)}
          >
            {item.label}
          </a>
        ))}
      </nav>

      <div className="page-sections">
        <section className="scroll-section target-section" id={sectionAnchorId("target")}>
          <TargetSelector
            activeOs={activeOs}
            activeTarget={activeTarget}
            targetSelected={targetSelected}
            targetVersion={activeTargetVersion}
            onChange={switchOs}
            onTargetSelected={() => setTargetSelected(true)}
            onVersionChange={(version) =>
              setTargetVersions((current) => ({ ...current, [activeOs]: version }))
            }
          />
          {copyError && (
            <p className="copy-status" role="status">
              {copyError}
            </p>
          )}
        </section>

        <section className="scroll-section" id={sectionAnchorId("packages")}>
          <div className="content-stack">
            <section className="panel">
              <div className="panel-heading">
                <div>
                  <p className="section-label">Install groups</p>
                  <h2>Choose what the command does</h2>
                </div>
              </div>
              <div className="step-grid">
                {installSteps.map((step) => (
                  <label className="option-row" key={step.key}>
                    <input
                      type="checkbox"
                      checked={stepSelection[step.key]}
                      onChange={() =>
                        setStepSelection((current) => ({
                          ...current,
                          [step.key]: !current[step.key]
                        }))
                      }
                    />
                    <span>
                      <strong>{step.title}</strong>
                      <small>{step.description}</small>
                    </span>
                  </label>
                ))}
              </div>
            </section>

            <section className="panel">
              <div className="panel-heading package-heading">
                <div>
                  <p className="section-label">Package catalog</p>
                  <h2>{activeTarget.label} package names</h2>
                </div>
                <label className="search-field">
                  <span>Search</span>
                  <input
                    value={query}
                    onChange={(event) => setQuery(event.target.value)}
                    placeholder="package, group, or label"
                  />
                </label>
              </div>

              <div className="group-list">
                {selectedGroups.map(({ group, selectedCount, totalCount }) => (
                  <PackageGroupPanel
                    activeOs={activeOs}
                    expanded={expandedGroups[group.id] ?? false}
                    group={group}
                    key={group.id}
                    query={query}
                    selectedCount={selectedCount}
                    selectedPackageIds={selectedPackageIds}
                    totalCount={totalCount}
                    onExpand={(expanded) =>
                      setExpandedGroups((current) => ({ ...current, [group.id]: expanded }))
                    }
                    onPackageToggle={togglePackage}
                    onSelectAll={() => setGroupSelection(group.id, true)}
                    onSelectNone={() => setGroupSelection(group.id, false)}
                  />
                ))}
              </div>

              <label className="field custom-packages">
                <span>Custom {activeTarget.packageManager} packages</span>
                <input
                  value={customPackages}
                  onChange={(event) => setCustomPackages(event.target.value)}
                  placeholder="space or comma separated"
                  spellCheck={false}
                />
              </label>
            </section>
          </div>
        </section>

        <section className="scroll-section" id={sectionAnchorId("toolchains")}>
          <div className="content-stack">
            <section className="panel">
              <div className="panel-heading">
                <div>
                  <p className="section-label">Toolchains</p>
                  <h2>Containers and language runtimes</h2>
                </div>
              </div>
              <ToolchainControl
                activeId={dockerStrategy}
                enabled={dockerEnabled}
                label="Docker"
                onChange={(value) => setDockerStrategy(value as DockerStrategyId)}
                onEnabledChange={(enabled) => setDockerEnabled(enabled)}
                recommendedId="official"
                strategies={dockerStrategies}
              />
              <ToolchainControl
                activeId={nodeStrategy}
                enabled={nodeEnabled}
                label="Node"
                onChange={(value) => setNodeStrategy(value as NodeStrategyId)}
                onEnabledChange={setNodeEnabled}
                recommendedId="mise"
                strategies={nodeStrategies}
              />
              <ToolchainControl
                activeId={pythonStrategy}
                enabled={pythonEnabled}
                label="Python"
                onChange={(value) => setPythonStrategy(value as PythonStrategyId)}
                onEnabledChange={setPythonEnabled}
                recommendedId="system-uv"
                strategies={pythonStrategies}
              />
              <ToolchainControl
                activeId={javaStrategy}
                enabled={javaEnabled}
                label="Java"
                onChange={(value) => setJavaStrategy(value as JavaStrategyId)}
                onEnabledChange={setJavaEnabled}
                recommendedId="mise-temurin-21"
                strategies={javaStrategies}
              />
            </section>
          </div>
        </section>

        <section className="main-grid scroll-section" id={sectionAnchorId("configs")}>
          <div className="content-stack">
            <section className="panel">
              <div className="panel-heading">
                <div>
                  <p className="section-label">Config files</p>
                  <h2>Edit generated config content</h2>
                </div>
              </div>
              <div className="config-tabs">
                {(Object.keys(configDefinitions) as ConfigKey[]).map((key) => (
                  <button
                    className={activeConfig === key ? "active" : ""}
                    key={key}
                    type="button"
                    onClick={() => setActiveConfig(key)}
                  >
                    {configDefinitions[key].title}
                  </button>
                ))}
              </div>
              <ConfigPreferencePanel
                activeConfig={activeConfig}
                installTpm={installTpm}
                powerlevel10k={powerlevel10k}
                setInstallTpm={setInstallTpm}
                setPowerlevel10k={setPowerlevel10k}
              />
              <ConfigBlockEditor
                activeBlockId={activeConfigBlockIds[activeConfig]}
                blocks={configBlocks[activeConfig]}
                configKey={activeConfig}
                draggedBlock={draggedBlock}
                generatedContent={configContents[activeConfig]}
                onActiveBlockChange={(blockId) =>
                  setActiveConfigBlockIds((current) => ({ ...current, [activeConfig]: blockId }))
                }
                onBlockContentChange={(blockId, content) =>
                  updateConfigBlock(blockId, (block) => ({ ...block, content }))
                }
                onBlockDrop={dropConfigBlock}
                onBlockMove={moveConfigBlock}
                onBlockReset={resetConfigBlock}
                onBlockToggle={(blockId) =>
                  updateConfigBlock(blockId, (block) => ({ ...block, enabled: !block.enabled }))
                }
                onDragStart={(blockId) => setDraggedBlock({ configKey: activeConfig, blockId })}
              />
            </section>
          </div>
          <aside className="panel sticky-panel">
            <p className="section-label">Config output</p>
            <h2>{configDefinitions[activeConfig].path}</h2>
            <CommandBlock
              title="Write command"
              command={configCommand}
              copied={copied === "config-command"}
              onCopy={() => copyText("config-command", configCommand)}
            />
            <button
              className="wide-button"
              type="button"
              onClick={() => copyText("config-content", configContents[activeConfig])}
            >
              {copied === "config-content" ? "Copied" : "Copy file content"}
            </button>
          </aside>
        </section>

        <section className="main-grid scroll-section" id={sectionAnchorId("summary")}>
          <div className="content-stack">
            <SummaryView
              activeTarget={activeTarget}
              configContents={configContents}
              dockerEnabled={dockerEnabled}
              dockerStrategy={dockerStrategy}
              installTpm={installTpm}
              javaEnabled={javaEnabled}
              javaStrategy={javaStrategy}
              nodeEnabled={nodeEnabled}
              nodeStrategy={nodeStrategy}
              powerlevel10k={powerlevel10k}
              prepareSystem={prepareSystem}
              pythonEnabled={pythonEnabled}
              pythonStrategy={pythonStrategy}
              runInTmux={runInTmux}
              selectedPackageNames={selectedPackageNames}
              stepSelection={stepSelection}
              targetVersion={activeTargetVersion}
            />
          </div>
          <CommandPanel
            activeTarget={activeTarget}
            assumeYes={assumeYes}
            commandSet={commandSet}
            copied={copied}
            dockerEnabled={dockerEnabled}
            javaEnabled={javaEnabled}
            javaStrategy={javaStrategy}
            nodeEnabled={nodeEnabled}
            nodeStrategy={nodeStrategy}
            prepareSystem={prepareSystem}
            pythonEnabled={pythonEnabled}
            pythonStrategy={pythonStrategy}
            repoRef={repoRef}
            runInTmux={runInTmux}
            selectedPackageNames={selectedPackageNames}
            targetVersion={activeTargetVersion}
            setAssumeYes={setAssumeYes}
            setPrepareSystem={setPrepareSystem}
            setRepoRef={setRepoRef}
            setRunInTmux={setRunInTmux}
            onCopy={copyText}
          />
        </section>
      </div>
    </main>
  );
}

function TargetSelector({
  activeOs,
  activeTarget,
  targetSelected,
  targetVersion,
  onChange,
  onTargetSelected,
  onVersionChange
}: {
  activeOs: OsId;
  activeTarget: OsTarget;
  targetSelected: boolean;
  targetVersion: string;
  onChange: (osId: OsId) => void;
  onTargetSelected: () => void;
  onVersionChange: (version: string) => void;
}) {
  const [isChanging, setIsChanging] = useState(false);
  const versionNote =
    (activeTarget.versions.find((version) => version.value === targetVersion) ?? activeTarget.versions[0])
      ?.note ?? "Custom version";

  if (!targetSelected) {
    return (
      <section className="target-bar target-picker" aria-label="Operating system">
        <div>
          <p className="section-label">Target OS</p>
          <strong>Choose target</strong>
        </div>
        <div className="target-options compact" role="group" aria-label="Target OS choices">
          {catalog.osTargets.map((target) => (
            <button
              className={activeOs === target.id ? "target-button active" : "target-button"}
              key={target.id}
              type="button"
              onClick={() => {
                onChange(target.id);
                onTargetSelected();
              }}
            >
              <strong>{targetShortLabel(target)}</strong>
              <span>
                {defaultVersionForTarget(target)}
                {!target.implemented ? " preview" : ""}
              </span>
            </button>
          ))}
        </div>
      </section>
    );
  }

  return (
    <>
      <section className="target-bar target-selected-row" aria-label="Operating system">
        <p className="section-label">Target OS</p>
        <button className="target-pill active" type="button" onClick={() => setIsChanging(true)}>
          <strong>{targetShortLabel(activeTarget)}</strong>
          <span>
            {activeTarget.packageManager}
            {!activeTarget.implemented ? " preview" : ""}
          </span>
        </button>
        <label className="version-field target-version-field" title={versionNote}>
          <span>Version</span>
          <input
            list={`versions-${activeTarget.id}`}
            value={targetVersion}
            onChange={(event) => onVersionChange(event.target.value)}
            aria-label={`${targetShortLabel(activeTarget)} version`}
            spellCheck={false}
          />
          <datalist id={`versions-${activeTarget.id}`}>
            {activeTarget.versions.map((version) => (
              <option key={version.value} value={version.value}>
                {version.label}
              </option>
            ))}
          </datalist>
        </label>
        <button className="target-change-button" type="button" onClick={() => setIsChanging(true)}>
          Change target
        </button>
      </section>

      {isChanging && (
        <div className="modal-backdrop" role="presentation" onClick={() => setIsChanging(false)}>
          <section
            className="target-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="target-modal-title"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="modal-heading">
              <div>
                <p className="section-label">Target OS</p>
                <h2 id="target-modal-title">Change target OS</h2>
              </div>
              <button type="button" onClick={() => setIsChanging(false)}>
                Close
              </button>
            </div>
            <p className="target-warning">
              Changing target OS can reset command defaults and package names. Review the command after switching.
            </p>
            <div className="target-options compact" role="group" aria-label="Target OS choices">
              {catalog.osTargets.map((target) => (
                <button
                  className={activeOs === target.id ? "target-button active" : "target-button"}
                  key={target.id}
                  type="button"
                  onClick={() => {
                    onChange(target.id);
                    setIsChanging(false);
                  }}
                >
                  <strong>{targetShortLabel(target)}</strong>
                  <span>
                    {defaultVersionForTarget(target)}
                    {!target.implemented ? " preview" : ""}
                  </span>
                </button>
              ))}
            </div>
          </section>
        </div>
      )}
    </>
  );
}

function ThemeToggle({
  mode,
  onChange
}: {
  mode: ThemeMode;
  onChange: (mode: ThemeMode) => void;
}) {
  const nextMode: ThemeMode = mode === "dark" ? "light" : "dark";

  return (
    <button
      aria-label={`Switch to ${nextMode} theme`}
      className={`theme-icon-toggle ${mode}`}
      title={`Switch to ${nextMode} theme`}
      type="button"
      onClick={() => onChange(nextMode)}
    >
      <span className="theme-icon" aria-hidden="true" />
      <span className="visually-hidden">{mode} theme</span>
    </button>
  );
}

function ConfigPreferencePanel({
  activeConfig,
  installTpm,
  powerlevel10k,
  setInstallTpm,
  setPowerlevel10k
}: {
  activeConfig: ConfigKey;
  installTpm: boolean;
  powerlevel10k: boolean;
  setInstallTpm: (checked: boolean) => void;
  setPowerlevel10k: (checked: boolean) => void;
}) {
  if (activeConfig !== "zshrc" && activeConfig !== "tmux") {
    return null;
  }

  return (
    <div className="config-preferences">
      {activeConfig === "zshrc" && (
        <PreferenceToggle
          checked={powerlevel10k}
          description="Use Powerlevel10k as the generated zsh prompt theme."
          label="Powerlevel10k prompt"
          onChange={setPowerlevel10k}
        />
      )}
      {activeConfig === "tmux" && (
        <PreferenceToggle
          checked={installTpm}
          description="Install tmux plugin manager for the TPM block in .tmux.conf."
          label="Install TPM"
          onChange={setInstallTpm}
        />
      )}
    </div>
  );
}

function PackageGroupPanel({
  activeOs,
  expanded,
  group,
  query,
  selectedCount,
  selectedPackageIds,
  totalCount,
  onExpand,
  onPackageToggle,
  onSelectAll,
  onSelectNone
}: {
  activeOs: OsId;
  expanded: boolean;
  group: PackageGroup;
  query: string;
  selectedCount: number;
  selectedPackageIds: string[];
  totalCount: number;
  onExpand: (expanded: boolean) => void;
  onPackageToggle: (packageId: string) => void;
  onSelectAll: () => void;
  onSelectNone: () => void;
}) {
  const normalizedQuery = query.trim().toLowerCase();
  const packages = catalog.packages
    .filter((item) => item.group === group.id)
    .filter((item) => {
      if (!normalizedQuery) {
        return true;
      }
      const packageNames = packageNamesForOs(item, activeOs).join(" ");
      return `${group.title} ${item.label} ${item.id} ${packageNames}`
        .toLowerCase()
        .includes(normalizedQuery);
    });
  const shouldOpen = expanded || normalizedQuery.length > 0;

  if (normalizedQuery && packages.length === 0) {
    return null;
  }

  return (
    <details
      className="group-panel"
      open={shouldOpen}
      onToggle={(event) => onExpand(event.currentTarget.open)}
    >
      <summary>
        <span>
          <strong>{group.title}</strong>
          <small>{group.description}</small>
        </span>
        <em>
          {selectedCount}/{totalCount}
        </em>
      </summary>
      <div className="group-detail">
        <p>{group.description}</p>
        <div className="group-actions">
          <button type="button" onClick={onSelectAll}>
            Select group
          </button>
          <button type="button" onClick={onSelectNone}>
            Clear group
          </button>
        </div>
      </div>
      <div className="package-tree">
        {packages.map((item) => {
          const packageNames = packageNamesForOs(item, activeOs);
          const hasPackageForOs = packageNames.length > 0;
          return (
            <label className="package-tree-row" key={item.id}>
              <input
                type="checkbox"
                checked={selectedPackageIds.includes(item.id)}
                disabled={!hasPackageForOs}
                onChange={() => onPackageToggle(item.id)}
              />
              <span className="tree-branch" aria-hidden="true" />
              <span className="package-row-copy">
                <strong>{item.label}</strong>
                <small>{packageDescriptionFor(item, group)}</small>
                <code>{hasPackageForOs ? packageNames.join(", ") : "No package needed"}</code>
              </span>
            </label>
          );
        })}
      </div>
    </details>
  );
}

function ToggleSwitch({
  checked,
  label,
  onChange
}: {
  checked: boolean;
  label: string;
  onChange: (checked: boolean) => void;
}) {
  return (
    <button
      className={checked ? "toggle-switch on" : "toggle-switch"}
      role="switch"
      aria-checked={checked}
      type="button"
      onClick={() => onChange(!checked)}
    >
      <span aria-hidden="true" />
      <strong>{label}</strong>
    </button>
  );
}

function PreferenceToggle({
  checked,
  description,
  label,
  onChange
}: {
  checked: boolean;
  description: string;
  label: string;
  onChange: (checked: boolean) => void;
}) {
  return (
    <div className="preference-card">
      <div>
        <strong>{label}</strong>
        <small>{description}</small>
      </div>
      <ToggleSwitch checked={checked} label={checked ? "On" : "Off"} onChange={onChange} />
    </div>
  );
}

function ToolchainControl({
  activeId,
  enabled,
  label,
  onChange,
  onEnabledChange,
  recommendedId,
  strategies
}: {
  activeId: string;
  enabled: boolean;
  label: string;
  onChange: (value: string) => void;
  onEnabledChange: (enabled: boolean) => void;
  recommendedId?: string;
  strategies: Strategy[];
}) {
  const [editing, setEditing] = useState(false);
  const activeStrategy = strategies.find((strategy) => strategy.id === activeId) ?? strategies[0];
  const setEnabled = (checked: boolean) => {
    if (!checked) {
      setEditing(false);
    }
    onEnabledChange(checked);
  };

  return (
    <div className="strategy-block">
      <div className="strategy-heading">
        <div>
          <h3>{label}</h3>
          {enabled && <p className="muted compact-note">{activeStrategy.description}</p>}
        </div>
        <ToggleSwitch checked={enabled} label={enabled ? "On" : "Off"} onChange={setEnabled} />
      </div>

      {enabled && (
        <div className="selected-strategy-card">
          <div>
            <strong>{activeStrategy.label}</strong>
            <small>{activeStrategy.description}</small>
          </div>
          <button type="button" onClick={() => setEditing((current) => !current)}>
            {editing ? "Close" : "Modify"}
          </button>
        </div>
      )}

      {enabled && editing && (
        <div className="strategy-grid">
          {strategies.map((strategy) => (
            <button
              className={activeId === strategy.id ? "strategy-card active" : "strategy-card"}
              key={strategy.id}
              type="button"
              onClick={() => onChange(strategy.id)}
            >
              <strong>
                {strategy.label}
                {strategy.id === recommendedId && <small>Recommended</small>}
              </strong>
              <span>{strategy.description}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function ConfigBlockEditor({
  activeBlockId,
  blocks,
  configKey,
  draggedBlock,
  generatedContent,
  onActiveBlockChange,
  onBlockContentChange,
  onBlockDrop,
  onBlockMove,
  onBlockReset,
  onBlockToggle,
  onDragStart
}: {
  activeBlockId: string;
  blocks: ConfigBlock[];
  configKey: ConfigKey;
  draggedBlock: DraggedBlock;
  generatedContent: string;
  onActiveBlockChange: (blockId: string) => void;
  onBlockContentChange: (blockId: string, content: string) => void;
  onBlockDrop: (blockId: string) => void;
  onBlockMove: (blockId: string, direction: -1 | 1) => void;
  onBlockReset: (blockId: string) => void;
  onBlockToggle: (blockId: string) => void;
  onDragStart: (blockId: string) => void;
}) {
  const activeBlock = blocks.find((block) => block.id === activeBlockId) ?? blocks[0];
  const activeIndex = blocks.findIndex((block) => block.id === activeBlock.id);
  const [selectedLine, setSelectedLine] = useState<{ blockId: string; lineIndex: number } | null>(null);
  const lineStarts = new Map<string, number>();
  let nextLineNumber = 1;

  for (const block of blocks) {
    const lineCount = block.content.trimEnd().split(/\r?\n/).length || 1;
    lineStarts.set(block.id, nextLineNumber);
    nextLineNumber += lineCount + 1;
  }

  const selectedLineBlock = selectedLine
    ? blocks.find((block) => block.id === selectedLine.blockId)
    : undefined;
  const detailLineBlock = selectedLineBlock ?? activeBlock;
  const detailLineIndex = selectedLineBlock && selectedLine ? selectedLine.lineIndex : 0;
  const selectedLineText = detailLineBlock.content.trimEnd().split(/\r?\n/)[detailLineIndex] || "";
  const selectedLineNumber = (lineStarts.get(detailLineBlock.id) ?? 1) + detailLineIndex;
  const activePluginNote = pluginNoteFor(configKey, activeBlock.id);

  return (
    <div className="config-builder">
      <div className="config-code-pane" aria-label={`${configDefinitions[configKey].title} blocks`}>
        <div className="code-pane-header">
          <strong>{configDefinitions[configKey].title}</strong>
          <span>
            {blocks.filter((block) => block.enabled).length}/{blocks.length} blocks on
          </span>
        </div>
        {blocks.map((block, index) => (
          <div
            className={[
              "editor-block",
              block.id === activeBlock.id ? "active" : "",
              block.enabled ? "" : "disabled",
              `kind-${block.kind}`,
              draggedBlock?.blockId === block.id ? "dragging" : ""
            ]
              .filter(Boolean)
              .join(" ")}
            draggable
            key={block.id}
            onClick={() => onActiveBlockChange(block.id)}
            onDragOver={(event) => event.preventDefault()}
            onDragStart={() => onDragStart(block.id)}
            onDrop={() => onBlockDrop(block.id)}
          >
            <div className="editor-block-header">
              <button
                className="block-title-button"
                type="button"
                onClick={() => {
                  setSelectedLine(null);
                  onActiveBlockChange(block.id);
                }}
              >
                <span>{block.title}</span>
                <small>{block.description}</small>
                <span className={`block-kind-pill kind-${block.kind}`}>{blockKindLabels[block.kind]}</span>
              </button>
              <div className="editor-block-actions">
                <button
                  aria-label={`Move ${block.title} up`}
                  className="icon-button"
                  disabled={index === 0}
                  type="button"
                  onClick={(event) => {
                    event.stopPropagation();
                    onBlockMove(block.id, -1);
                  }}
                >
                  Up
                </button>
                <button
                  aria-label={`Move ${block.title} down`}
                  className="icon-button"
                  disabled={index === blocks.length - 1}
                  type="button"
                  onClick={(event) => {
                    event.stopPropagation();
                    onBlockMove(block.id, 1);
                  }}
                >
                  Down
                </button>
                <button
                  className={block.enabled ? "block-toggle on" : "block-toggle"}
                  role="switch"
                  aria-checked={block.enabled}
                  type="button"
                  onClick={(event) => {
                    event.stopPropagation();
                    onBlockToggle(block.id);
                  }}
                >
                  <span aria-hidden="true" />
                  <strong>{block.enabled ? "On" : "Off"}</strong>
                </button>
              </div>
            </div>
            <div className="editor-lines">
              {(block.content.trimEnd().split(/\r?\n/) || [""]).map((line, lineIndex) => {
                const lineNumber = (lineStarts.get(block.id) ?? 1) + lineIndex;
                const lineKey = `${block.id}-${lineIndex}`;
                const lineActive = selectedLine?.blockId === block.id && selectedLine.lineIndex === lineIndex;
                return (
                  <button
                    className={lineActive ? "code-line active" : "code-line"}
                    key={lineKey}
                    type="button"
                    onClick={(event) => {
                      event.stopPropagation();
                      setSelectedLine({ blockId: block.id, lineIndex });
                      onActiveBlockChange(block.id);
                    }}
                  >
                    <span className="line-number">{lineNumber}</span>
                    <code className="line-text">{line || " "}</code>
                  </button>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      <section className="block-detail" aria-label="Selected config block">
        <div className="block-detail-heading">
          <div>
            <p className="section-label">Selected block</p>
            <h3>{activeBlock.title}</h3>
          </div>
          <span className="block-position">
            {activeIndex + 1}/{blocks.length}
          </span>
        </div>
        <p className="muted">{activeBlock.description}</p>
        <div className="block-meta-row">
          <span className={`block-kind-pill kind-${activeBlock.kind}`}>{blockKindLabels[activeBlock.kind]}</span>
          <span className="meta-chip">{blockKindDescriptions[activeBlock.kind]}</span>
        </div>
        {activeBlock.risk && <p className="order-warning">{activeBlock.risk}</p>}
        {activePluginNote && <p className="plugin-note">{activePluginNote}</p>}
        {activeBlock.shortcuts.length > 0 && <KeycapList keys={activeBlock.shortcuts} />}
        <div className="selected-line-detail">
          <span>Line {selectedLineNumber}</span>
          <code>{selectedLineText || "blank line"}</code>
        </div>
        <textarea
          className="block-editor"
          spellCheck={false}
          value={activeBlock.content}
          onChange={(event) => onBlockContentChange(activeBlock.id, event.target.value)}
        />
        <div className="block-actions">
          <button type="button" onClick={() => onBlockMove(activeBlock.id, -1)} disabled={activeIndex === 0}>
            Move up
          </button>
          <button
            type="button"
            onClick={() => onBlockMove(activeBlock.id, 1)}
            disabled={activeIndex === blocks.length - 1}
          >
            Move down
          </button>
          <button type="button" onClick={() => onBlockReset(activeBlock.id)}>
            Reset block
          </button>
        </div>
        <details className="generated-config">
          <summary>Generated file text</summary>
          <textarea className="config-editor" readOnly spellCheck={false} value={generatedContent} />
        </details>
      </section>
    </div>
  );
}

function pluginNoteFor(configKey: ConfigKey, blockId: string) {
  if (configKey === "vimrc" && blockId === "plugins") {
    return "vim-plug is installed by the setup script. This rc block only uses it when plug.vim already exists.";
  }
  if (configKey === "tmux" && blockId === "tpm") {
    return "TPM stays commented by default. Install TPM, uncomment this block, then press prefix plus I to install plugins.";
  }
  return "";
}

function KeycapList({ keys }: { keys: string[] }) {
  return (
    <div className="keycap-list" aria-label="Keyboard shortcuts">
      {keys.map((keyName) => (
        <kbd key={keyName}>{keyName}</kbd>
      ))}
    </div>
  );
}

function CommandPanel({
  activeTarget,
  assumeYes,
  commandSet,
  copied,
  dockerEnabled,
  javaEnabled,
  javaStrategy,
  nodeEnabled,
  nodeStrategy,
  prepareSystem,
  pythonEnabled,
  pythonStrategy,
  repoRef,
  runInTmux,
  selectedPackageNames,
  targetVersion,
  setAssumeYes,
  setPrepareSystem,
  setRepoRef,
  setRunInTmux,
  onCopy
}: {
  activeTarget: OsTarget;
  assumeYes: boolean;
  commandSet: CommandSet;
  copied: string | null;
  dockerEnabled: boolean;
  javaEnabled: boolean;
  javaStrategy: JavaStrategyId;
  nodeEnabled: boolean;
  nodeStrategy: NodeStrategyId;
  prepareSystem: boolean;
  pythonEnabled: boolean;
  pythonStrategy: PythonStrategyId;
  repoRef: string;
  runInTmux: boolean;
  selectedPackageNames: string[];
  targetVersion: string;
  setAssumeYes: (value: boolean) => void;
  setPrepareSystem: (value: boolean) => void;
  setRepoRef: (value: string) => void;
  setRunInTmux: (value: boolean) => void;
  onCopy: (key: string, value: string) => void;
}) {
  return (
    <aside className="panel sticky-panel">
      <p className="section-label">Command</p>
      <h2>{activeTarget.implemented ? "Run from terminal" : "Preview command"}</h2>
      <p className="muted">{activeTarget.note}</p>
      <label className="field">
        <span>Repository ref</span>
        <input value={repoRef} onChange={(event) => setRepoRef(event.target.value)} spellCheck={false} />
      </label>
      <label className="switch-row">
        <input type="checkbox" checked={assumeYes} onChange={() => setAssumeYes(!assumeYes)} />
        <span>Use --yes</span>
      </label>
      <div className="command-run-options">
        <label>
          <input
            type="checkbox"
            checked={prepareSystem}
            onChange={() => setPrepareSystem(!prepareSystem)}
          />
          <span>Update first</span>
        </label>
        <label>
          <input type="checkbox" checked={runInTmux} onChange={() => setRunInTmux(!runInTmux)} />
          <span>Run in tmux</span>
        </label>
      </div>
      <p className="muted compact-note">Target version: {targetVersion || "not set"}</p>
      <p className="muted compact-note">Docker install: {dockerEnabled ? "on" : "off"}</p>
      <p className="muted compact-note">Node setup: {nodeEnabled ? nodeStrategy : "off"}</p>
      <p className="muted compact-note">Python setup: {pythonEnabled ? pythonStrategy : "off"}</p>
      <p className="muted compact-note">Java install: {javaEnabled ? javaStrategy : "off"}</p>
      <div className="mini-summary">
        <strong>{selectedPackageNames.length}</strong>
        <span>{activeTarget.packageManager} packages selected</span>
      </div>
      <CommandBlock
        title={activeTarget.implemented ? "Bootstrap command" : "Package command"}
        command={activeTarget.implemented ? commandSet.primary : commandSet.packageCommand}
        copied={copied === "primary-command"}
        onCopy={() =>
          onCopy("primary-command", activeTarget.implemented ? commandSet.primary : commandSet.packageCommand)
        }
      />
      {activeTarget.implemented && (
        <CommandBlock
          title="Already cloned"
          command={commandSet.local}
          copied={copied === "local-command"}
          onCopy={() => onCopy("local-command", commandSet.local)}
        />
      )}
    </aside>
  );
}

function SummaryView({
  activeTarget,
  configContents,
  dockerEnabled,
  dockerStrategy,
  installTpm,
  javaEnabled,
  javaStrategy,
  nodeEnabled,
  nodeStrategy,
  powerlevel10k,
  prepareSystem,
  pythonEnabled,
  pythonStrategy,
  runInTmux,
  selectedPackageNames,
  stepSelection,
  targetVersion
}: {
  activeTarget: OsTarget;
  configContents: Record<ConfigKey, string>;
  dockerEnabled: boolean;
  dockerStrategy: DockerStrategyId;
  installTpm: boolean;
  javaEnabled: boolean;
  javaStrategy: JavaStrategyId;
  nodeEnabled: boolean;
  nodeStrategy: NodeStrategyId;
  powerlevel10k: boolean;
  prepareSystem: boolean;
  pythonEnabled: boolean;
  pythonStrategy: PythonStrategyId;
  runInTmux: boolean;
  selectedPackageNames: string[];
  stepSelection: Record<InstallStepKey, boolean>;
  targetVersion: string;
}) {
  const configLineCounts = (Object.keys(configContents) as ConfigKey[]).map((key) => ({
    key,
    title: configDefinitions[key].title,
    lines: configContents[key].split(/\r?\n/).length
  }));

  return (
    <section className="summary-grid">
      <section className="panel">
        <p className="section-label">Summary</p>
        <h2>{activeTarget.label}</h2>
        <dl className="summary-list">
          <div>
            <dt>Package manager</dt>
            <dd>{activeTarget.packageManager}</dd>
          </div>
          <div>
            <dt>Target version</dt>
            <dd>{targetVersion || "not set"}</dd>
          </div>
          <div>
            <dt>Install steps</dt>
            <dd>{Object.entries(stepSelection).filter(([, enabled]) => enabled).map(([key]) => key).join(", ")}</dd>
          </div>
          <div>
            <dt>Docker strategy</dt>
            <dd>{dockerEnabled ? dockerStrategy : "off"}</dd>
          </div>
          <div>
            <dt>Node strategy</dt>
            <dd>{nodeEnabled ? nodeStrategy : "off"}</dd>
          </div>
          <div>
            <dt>Python strategy</dt>
            <dd>{pythonEnabled ? pythonStrategy : "off"}</dd>
          </div>
          <div>
            <dt>Java strategy</dt>
            <dd>{javaEnabled ? javaStrategy : "off"}</dd>
          </div>
          <div>
            <dt>Powerlevel10k</dt>
            <dd>{powerlevel10k ? "on" : "off"}</dd>
          </div>
          <div>
            <dt>TPM</dt>
            <dd>{installTpm ? "install" : "off"}</dd>
          </div>
          <div>
            <dt>Run wrapper</dt>
            <dd>{[prepareSystem ? "update first" : "", runInTmux ? "tmux" : ""].filter(Boolean).join(", ") || "off"}</dd>
          </div>
          <div>
            <dt>Selected packages</dt>
            <dd>{selectedPackageNames.length}</dd>
          </div>
        </dl>
      </section>
      <section className="panel">
        <p className="section-label">Packages</p>
        <h2>Resolved names</h2>
        {selectedPackageNames.length > 0 ? (
          <div className="selected-package-list">
            {selectedPackageNames.map((name) => (
              <span key={name}>{name}</span>
            ))}
          </div>
        ) : (
          <p className="muted">No package-manager packages selected.</p>
        )}
      </section>
      <section className="panel">
        <p className="section-label">Configs</p>
        <h2>Editable files</h2>
        <ul className="plain-list">
          {configLineCounts.map((item) => (
            <li key={item.key}>
              {item.title}: {item.lines} lines
            </li>
          ))}
        </ul>
      </section>
    </section>
  );
}

type CommandBlockProps = {
  title: string;
  command: string;
  copied: boolean;
  onCopy: () => void;
};

function CommandBlock({ title, command, copied, onCopy }: CommandBlockProps) {
  return (
    <div className="command-block">
      <div className="command-header">
        <h3>{title}</h3>
        <button type="button" aria-label={`Copy ${title}`} onClick={onCopy}>
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
      <pre>
        <code>{command}</code>
      </pre>
    </div>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
